### ISSUE TITLE
Hook method onPluginInstall doesn't get the installedSchema as param

### ISSUE THREAD

**Issue by AWessel77** [mautic/mautic#11072]
### Mautic Version

4.1.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I got an errror on plugin installation that occured because the param $installedSchema for the hook method onPluginInstall is not the schema. Instead it is a bollean.

### How can we reproduce this issue?

The ReloadHelper provides different parameters when calling the hook methods **onPluginInstall** and **onPluginUpdate**, although the signature of the methods look similar and parameters of the calls also.

Calls of the hook methods:
```php
$callback::onPluginInstall($entity, $this->factory, $metadata, $installedSchema);
```
```php
$callback::onPluginUpdate($plugin, $this->factory, $metadata, $installedSchema);
```

For **onPluginInstall** param **$installedSchema** is a boolean, for **onPluginUpdate** it is the installed schema.

### Relevant log output

```shell
[2022-04-13 07:43:19] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Argument 2 passed to MauticPlugin\HowToStopPutinBundle\HowToStopPutinBundle::methodThatUsesInstalledSchema() must be an instance of Doctrine\DBAL\Schema\Schema or null, bool given, called in /var/www/html/plugins/HowToStopPutinBundle/HowToStopPutinBundle.php on line 65" at /var/www/html/plugins/HowToStopPutinBundle/HowToStopPutinBundle.php line 76 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 2 passed to MauticPlugin\\HowToStopPutinBundle\\HowToStopPutinBundle::methodThatUsesInstalledSchema() must be an instance of Doctrine\\DBAL\\Schema\\Schema or null, bool given, called in /var/www/html/plugins/HowToStopPutinBundle/HowToStopPutinBundle.php on line 65 at /var/www/html/plugins/HowToStopPutinBundle/HowToStopPutinBundle.php:76)
[stacktrace]
#0 /var/www/html/plugins/HowToStopPutinBundle/HowToStopPutinBundle.php(65): MauticPlugin\\HowToStopPutinBundle\\HowToStopPutinBundle::methodThatUsesInstalledSchema(Object(Mautic\\CoreBundle\\Factory\\MauticFactory), true)

### This is relevant

#1 /var/www/html/app/bundles/PluginBundle/Helper/ReloadHelper.php(131): MauticPlugin\\GcsPluginWebinarRegistrationBundle\\GcsPluginWebinarRegistrationBundle::onPluginInstall(Object(Mautic\\PluginBundle\\Entity\\Plugin), Object(Mautic\\CoreBundle\\Factory\\MauticFactory), Array, true)
#2 /var/www/html/app/bundles/PluginBundle/Facade/ReloadFacade.php(49): Mautic\\PluginBundle\\Helper\\ReloadHelper->installPlugins(Array, Array, Array, Array)

### This is relevant - End

#3 /var/www/html/app/bundles/PluginBundle/Controller/PluginController.php(425): Mautic\\PluginBundle\\Facade\\ReloadFacade->reloadPlugins()
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\PluginBundle\\Controller\\PluginController->reloadAction()
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#14 /var/www/html/index.php(24): Stack\
un(Object(Stack\\StackedHttpKernel))
#15 {main}
"}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the bug report @AWessel77 - any chance you would be up for digging into the code and seeing if you can make a PR?

Not sure if it helps but we have some much updated documentation in our WIP migration to Read the Docs on plugins which may also be of assistance: https://mautic-developer.readthedocs.io/en/latest/plugins/getting_started.html
