### ISSUE TITLE
Error using 'push contact to integration' form action

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11245]
### Mautic Version

4.3.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When documenting the push to integration form action I noticed the following error in dev mode:

![Desktop screenshot (14)](https://user-images.githubusercontent.com/2930593/173371200-e397632a-56c2-452f-885c-f1c336b0919a.png)

I have the Hubspot integration set up, so there should be an integration available to use.

### How can we reproduce this issue?

Step 1: Set up an integration
Step 2: Create a form, add a form action of Push to integration (in dev mode)

### Relevant log output

```shell
[2022-06-13 13:58:39] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - Trying to access array offset on value of type null" at /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php line 102 {"exception":"[object] (ErrorException(code: 0): PHP Notice - Trying to access array offset on value of type null at /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php:102)
[stacktrace]
#0 /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php(102): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Tr...', '/var/www/html/a...', 102, Array)
#1 /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php(127): Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType->Mautic\\PluginBundle\\Form\\Type\\{closure}(Object(Symfony\\Component\\Form\\Form), NULL)
#2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType->Mautic\\PluginBundle\\Form\\Type\\{closure}(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'form.pre_set_da...', Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent))
#4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'form.pre_set_da...', Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent))
#5 /var/www/html/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...')
#6 /var/www/html/vendor/symfony/form/Form.php(353): Symfony\\Component\\EventDispatcher\\ImmutableEventDispatcher->dispatch(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...')
#7 /var/www/html/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php(51): Symfony\\Component\\Form\\Form->setData(NULL)
#8 /var/www/html/vendor/symfony/form/Form.php(389): Symfony\\Component\\Form\\Extension\\Core\\DataMapper\\PropertyPathMapper->mapDataToForms(Array, Object(RecursiveIteratorIterator))
#9 /var/www/html/vendor/symfony/form/Form.php(493): Symfony\\Component\\Form\\Form->setData(Array)
#10 /var/www/html/vendor/symfony/form/FormBuilder.php(208): Symfony\\Component\\Form\\Form->initialize()
#11 /var/www/html/vendor/symfony/form/FormFactory.php(32): Symfony\\Component\\Form\\FormBuilder->getForm()
#12 /var/www/html/app/bundles/FormBundle/Controller/ActionController.php(53): Symfony\\Component\\Form\\FormFactory->create('Mautic\\\\FormBund...', Array, Array)
#13 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(447): Mautic\\FormBundle\\Controller\\ActionController->newAction(0, '')
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#15 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#16 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#25 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#26 {main}
"} {"hostname":"mautic-web","pid":2084}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by lexsoft00** [comment]
Mautic version 4.3.1
PHP 7.4

Having same issues with MailChimp plugin using dev mode.

```
[2022-06-27 12:44:57] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - Trying to access array offset on value of type null" at /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php line 102 {"exception":"[object] (ErrorException(code: 0): PHP Notice - Trying to access array offset on value of type null at /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php:102)
[stacktrace]
#0 /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php(102): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Tr...', '/var/www/html/a...', 102, Array)
#1 /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php(127): Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType->Mautic\\PluginBundle\\Form\\Type\\{closure}(Object(Symfony\\Component\\Form\\Form), NULL)
#2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType->Mautic\\PluginBundle\\Form\\Type\\{closure}(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'form.pre_set_da...', Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent))
#4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'form.pre_set_da...', Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent))
#5 /var/www/html/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...')
#6 /var/www/html/vendor/symfony/form/Form.php(353): Symfony\\Component\\EventDispatcher\\ImmutableEventDispatcher->dispatch(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...')
#7 /var/www/html/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php(51): Symfony\\Component\\Form\\Form->setData(NULL)
#8 /var/www/html/vendor/symfony/form/Form.php(389): Symfony\\Component\\Form\\Extension\\Core\\DataMapper\\PropertyPathMapper->mapDataToForms(Array, Object(RecursiveIteratorIterator))
#9 /var/www/html/vendor/symfony/form/Form.php(493): Symfony\\Component\\Form\\Form->setData(Array)
#10 /var/www/html/vendor/symfony/form/FormBuilder.php(208): Symfony\\Component\\Form\\Form->initialize()
#11 /var/www/html/vendor/symfony/form/FormFactory.php(32): Symfony\\Component\\Form\\FormBuilder->getForm()
#12 /var/www/html/app/bundles/FormBundle/Controller/ActionController.php(53): Symfony\\Component\\Form\\FormFactory->create('Mautic\\\\FormBund...', Array, Array)
#13 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(447): Mautic\\FormBundle\\Controller\\ActionController->newAction(0, '')
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#15 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#16 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#25 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#26 {main}
"} {"hostname":"mautic-web","pid":2418}
```
