### ISSUE TITLE
Unable to send segment mails on 5.x branch in Gitpod

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11490]
### Mautic Version

5.0.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When trying to send a segment email testing against the default branch (5.x) they are not being sent and an error is thrown in the logs.

### How can we reproduce this issue?

Step 1: Create a segment
Step 2: Create a segment email
Step 3: Send the segment email

Oops ... nothing happens, email isn't sent.

### Relevant log output

```shell
[2022-09-22 12:12:35] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - unserialize(): Error at offset 161509 of 161522 bytes" at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 126 {"exception":"[object] (ErrorException(code: 0): PHP Notice - unserialize(): Error at offset 161509 of 161522 bytes at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:126)
[stacktrace]
#0 [internal function]: Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - un...', '/var/www/html/v...', 126, Array)
#1 /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php(126): unserialize('a:9:{s:5:\"token...')
#2 /var/www/html/vendor/symfony/http-kernel/Profiler/Profiler.php(87): Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage->read('9d33d1')
#3 /var/www/html/vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php(153): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->loadProfile('9d33d1')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Symfony\\Bundle\\WebProfilerBundle\\Controller\\ProfilerController->toolbarAction(Object(Symfony\\Component\\HttpFoundation\\Request), '9d33d1')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#15 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#16 {main}
"} {"hostname":"mautic-web","pid":3783}
[2022-09-22 12:13:40] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - unserialize(): Error at offset 1844277 of 1844435 bytes" at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 126 {"exception":"[object] (ErrorException(code: 0): PHP Notice - unserialize(): Error at offset 1844277 of 1844435 bytes at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:126)
[stacktrace]
#0 [internal function]: Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - un...', '/var/www/html/v...', 126, Array)
#1 /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php(126): unserialize('a:9:{s:5:\"token...')
#2 /var/www/html/vendor/symfony/http-kernel/Profiler/Profiler.php(87): Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage->read('959b64')
#3 /var/www/html/vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php(153): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->loadProfile('959b64')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Symfony\\Bundle\\WebProfilerBundle\\Controller\\ProfilerController->toolbarAction(Object(Symfony\\Component\\HttpFoundation\\Request), '959b64')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#15 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#16 {main}
"} {"hostname":"mautic-web","pid":2269}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by volha-pivavarchyk** [comment]
@RCheesley The [PR #11595](https://github.com/mautic/mautic/pull/11595) fixes this issue. I added a description of where it came from. It was my bad :(

Im not sure if the log error relates to this issue too.

**Comment by RCheesley** [comment]
The PR fixes the issue with not being able to send segment emails, and there is no log message so guessing that is something else!
