### ISSUE TITLE
500 error inserting into email_stats - Failed to read auto-increment value from storage engine 

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11741]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

This is happening intermittently, and it is hard to know exactly what is causing it, but I've seen it multiple times today.

Sending emails during testing and at some point they just stop sending and I see this error in the logs:

```
  [2022-11-23 13:41:41] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO email_stats (email_address, date_sent, is_read, is_failed, viewed_in_browser, date_read, tracking_hash, retry_count, source, source_id, tokens, open_count, last_opened, open_details, email_id, lead_id, list_id, ip_id, copy_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["JeremyJNewell@fleckens.hu", "2022-11-23 13:41:41", 0, 0, 0, null, "637e2315ac8b8328433211", 0, "email", 2, "a:13:{s:36:\"{dynamiccontent=\"Dynamic Content 1\"}\";s:23:\"Default Dynamic Content\";s:18:\"{unsubscribe_text}\";s:174:\"<a href='https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/unsubscribe\/637e2315ac8b8328433211'>Unsubscribe<\/a> to no longer receive emails from us.\";s:17:\"{unsubscribe_url}\";s:111:\"https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/unsubscribe\/637e2315ac8b8328433211\";s:14:\"{webview_text}\";s:165:\"<a href='https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/view\/637e2315ac8b8328433211'>Having trouble reading this email? Click here.<\/a>\";s:13:\"{webview_url}\";s:104:\"https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/view\/637e2315ac8b8328433211\";s:11:\"{signature}\";s:0:\"\";s:9:\"{subject}\";s:45:\"Join us at the 2014  Kaleidoscope Conference!\";s:18:\"{ownerfield=email}\";s:18:\"sales@yoursite.com\";s:22:\"{ownerfield=firstname}\";s:5:\"Sales\";s:21:\"{ownerfield=lastname}\";s:4:\"User\";s:21:\"{ownerfield=position}\";s:0:\"\";s:22:\"{ownerfield=signature}\";s:0:\"\";s:16:\"{tracking_pixel}\";s:103:\"https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/637e2315ac8b8328433211.gif\";}", 0, null, "a:0:{}", 2, "38", 8, null, "36063129a95501d2e6ceeb166b4d1a78"]:
  
  SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO email_stats (email_address, date_sent, is_read, is_failed, viewed_in_browser, date_read, tracking_hash, retry_count, source, source_id, tokens, open_count, last_opened, open_details, email_id, lead_id, list_id, ip_id, copy_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"JeremyJNewell@fleckens.hu\", \"2022-11-23 13:41:41\", 0, 0, 0, null, \"637e2315ac8b8328433211\", 0, \"email\", 2, \"a:13:{s:36:\\\"{dynamiccontent=\\\"Dynamic Content 1\\\"}\\\";s:23:\\\"Default Dynamic Content\\\";s:18:\\\"{unsubscribe_text}\\\";s:174:\\\"<a href='https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/unsubscribe\\/637e2315ac8b8328433211'>Unsubscribe<\\/a> to no longer receive emails from us.\\\";s:17:\\\"{unsubscribe_url}\\\";s:111:\\\"https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/unsubscribe\\/637e2315ac8b8328433211\\\";s:14:\\\"{webview_text}\\\";s:165:\\\"<a href='https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/view\\/637e2315ac8b8328433211'>Having trouble reading this email? Click here.<\\/a>\\\";s:13:\\\"{webview_url}\\\";s:104:\\\"https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/view\\/637e2315ac8b8328433211\\\";s:11:\\\"{signature}\\\";s:0:\\\"\\\";s:9:\\\"{subject}\\\";s:45:\\\"Join us at the 2014  Kaleidoscope Conference!\\\";s:18:\\\"{ownerfield=email}\\\";s:18:\\\"sales@yoursite.com\\\";s:22:\\\"{ownerfield=firstname}\\\";s:5:\\\"Sales\\\";s:21:\\\"{ownerfield=lastname}\\\";s:4:\\\"User\\\";s:21:\\\"{ownerfield=position}\\\";s:0:\\\"\\\";s:22:\\\"{ownerfield=signature}\\\";s:0:\\\"\\\";s:16:\\\"{tracking_pixel}\\\";s:103:\\\"https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/637e2315ac8b8328433211.gif\\\";}\", 0, null, \"a:0:{}\", 2, \"38\", 8, null, \"36063129a95501d2e6ceeb166b4d1a78\"]:
  
  SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: HY000): SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
  [stacktrace]
  #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDO\\Exception))
  #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'An exception oc...')
  #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'INSERT INTO ema...', Array)
  #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(185): Doctrine\\DBAL\\Connection->handleExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'INSERT INTO ema...', Array, Array)
  #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(226): Doctrine\\DBAL\\Statement->execute(NULL)
  #5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(278): Doctrine\\DBAL\\Statement->executeStatement()
  #6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1133): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->executeInserts()
  #7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(430): Doctrine\\ORM\\UnitOfWork->executeInserts(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
  #8 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(403): Doctrine\\ORM\\UnitOfWork->commit(Object(Mautic\\EmailBundle\\Entity\\Stat))
  #9 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(796): Doctrine\\ORM\\EntityManager->flush(Object(Mautic\\EmailBundle\\Entity\\Stat))
  #10 /var/www/html/app/bundles/EmailBundle/Stat/StatHelper.php(41): Mautic\\CoreBundle\\Entity\\CommonRepository->saveEntity(Object(Mautic\\EmailBundle\\Entity\\Stat))
  #11 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(372): Mautic\\EmailBundle\\Stat\\StatHelper->storeStat(Object(Mautic\\EmailBundle\\Entity\\Stat), 'JeremyJNewell@f...')
  #12 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(422): Mautic\\EmailBundle\\Model\\SendEmailToContact->createContactStatEntry('JeremyJNewell@f...')
  #13 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(222): Mautic\\EmailBundle\\Model\\SendEmailToContact->sendStandardEmail()
  #14 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1505): Mautic\\EmailBundle\\Model\\SendEmailToContact->send()
  #15 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1136): Mautic\\EmailBundle\\Model\\EmailModel->sendEmail(Object(Mautic\\EmailBundle\\Entity\\Email), Array, Array)
  #16 /var/www/html/app/bundles/EmailBundle/Controller/AjaxController.php(59): Mautic\\EmailBundle\\Model\\EmailModel->sendEmailToLists(Object(Mautic\\EmailBundle\\Entity\\Email), Object(Doctrine\\ORM\\PersistentCollection), 92)
  #17 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(127): Mautic\\EmailBundle\\Controller\\AjaxController->sendBatchAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'email')
  #18 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('sendBatch', Object(Symfony\\Component\\HttpFoundation\\Request), 'email')
  #19 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
  #20 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(96): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
  #21 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(105): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->forward('Mautic\\\\EmailBun...', Array)
  #22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
  #23 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
  #24 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #25 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #26 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #27 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #28 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #29 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #30 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #31 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #32 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
  #33 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
  #34 /var/www/html/index_dev.php(25): Stack\
  un(Object(Stack\\StackedHttpKernel))
  #35 {main}
  "} {"hostname":"mautic-web","pid":2478}

```

### How can we reproduce this issue?

Step 1: Send a bunch of emails - in my case I am sending segment, campaign and marketing messages
Step 2: At some point they stop sending - it crashed for me with a 500 error when sending a segment message.

### Relevant log output

```shell
[2022-11-23 13:41:41] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO email_stats (email_address, date_sent, is_read, is_failed, viewed_in_browser, date_read, tracking_hash, retry_count, source, source_id, tokens, open_count, last_opened, open_details, email_id, lead_id, list_id, ip_id, copy_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["JeremyJNewell@fleckens.hu", "2022-11-23 13:41:41", 0, 0, 0, null, "637e2315ac8b8328433211", 0, "email", 2, "a:13:{s:36:\"{dynamiccontent=\"Dynamic Content 1\"}\";s:23:\"Default Dynamic Content\";s:18:\"{unsubscribe_text}\";s:174:\"<a href='https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/unsubscribe\/637e2315ac8b8328433211'>Unsubscribe<\/a> to no longer receive emails from us.\";s:17:\"{unsubscribe_url}\";s:111:\"https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/unsubscribe\/637e2315ac8b8328433211\";s:14:\"{webview_text}\";s:165:\"<a href='https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/view\/637e2315ac8b8328433211'>Having trouble reading this email? Click here.<\/a>\";s:13:\"{webview_url}\";s:104:\"https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/view\/637e2315ac8b8328433211\";s:11:\"{signature}\";s:0:\"\";s:9:\"{subject}\";s:45:\"Join us at the 2014  Kaleidoscope Conference!\";s:18:\"{ownerfield=email}\";s:18:\"sales@yoursite.com\";s:22:\"{ownerfield=firstname}\";s:5:\"Sales\";s:21:\"{ownerfield=lastname}\";s:4:\"User\";s:21:\"{ownerfield=position}\";s:0:\"\";s:22:\"{ownerfield=signature}\";s:0:\"\";s:16:\"{tracking_pixel}\";s:103:\"https:\/\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\/index_dev.php\/email\/637e2315ac8b8328433211.gif\";}", 0, null, "a:0:{}", 2, "38", 8, null, "36063129a95501d2e6ceeb166b4d1a78"]:

SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO email_stats (email_address, date_sent, is_read, is_failed, viewed_in_browser, date_read, tracking_hash, retry_count, source, source_id, tokens, open_count, last_opened, open_details, email_id, lead_id, list_id, ip_id, copy_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"JeremyJNewell@fleckens.hu\", \"2022-11-23 13:41:41\", 0, 0, 0, null, \"637e2315ac8b8328433211\", 0, \"email\", 2, \"a:13:{s:36:\\\"{dynamiccontent=\\\"Dynamic Content 1\\\"}\\\";s:23:\\\"Default Dynamic Content\\\";s:18:\\\"{unsubscribe_text}\\\";s:174:\\\"<a href='https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/unsubscribe\\/637e2315ac8b8328433211'>Unsubscribe<\\/a> to no longer receive emails from us.\\\";s:17:\\\"{unsubscribe_url}\\\";s:111:\\\"https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/unsubscribe\\/637e2315ac8b8328433211\\\";s:14:\\\"{webview_text}\\\";s:165:\\\"<a href='https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/view\\/637e2315ac8b8328433211'>Having trouble reading this email? Click here.<\\/a>\\\";s:13:\\\"{webview_url}\\\";s:104:\\\"https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/view\\/637e2315ac8b8328433211\\\";s:11:\\\"{signature}\\\";s:0:\\\"\\\";s:9:\\\"{subject}\\\";s:45:\\\"Join us at the 2014  Kaleidoscope Conference!\\\";s:18:\\\"{ownerfield=email}\\\";s:18:\\\"sales@yoursite.com\\\";s:22:\\\"{ownerfield=firstname}\\\";s:5:\\\"Sales\\\";s:21:\\\"{ownerfield=lastname}\\\";s:4:\\\"User\\\";s:21:\\\"{ownerfield=position}\\\";s:0:\\\"\\\";s:22:\\\"{ownerfield=signature}\\\";s:0:\\\"\\\";s:16:\\\"{tracking_pixel}\\\";s:103:\\\"https:\\/\\/8080-mautic-mautic-htqvd69aq4p.ws-eu77.gitpod.io\\/index_dev.php\\/email\\/637e2315ac8b8328433211.gif\\\";}\", 0, null, \"a:0:{}\", 2, \"38\", 8, null, \"36063129a95501d2e6ceeb166b4d1a78\"]:

SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: HY000): SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1467 Failed to read auto-increment value from storage engine at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDO\\Exception))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'An exception oc...')
#2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'INSERT INTO ema...', Array)
#3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(185): Doctrine\\DBAL\\Connection->handleExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'INSERT INTO ema...', Array, Array)
#4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(226): Doctrine\\DBAL\\Statement->execute(NULL)
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(278): Doctrine\\DBAL\\Statement->executeStatement()
#6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1133): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->executeInserts()
#7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(430): Doctrine\\ORM\\UnitOfWork->executeInserts(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
#8 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(403): Doctrine\\ORM\\UnitOfWork->commit(Object(Mautic\\EmailBundle\\Entity\\Stat))
#9 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(796): Doctrine\\ORM\\EntityManager->flush(Object(Mautic\\EmailBundle\\Entity\\Stat))
#10 /var/www/html/app/bundles/EmailBundle/Stat/StatHelper.php(41): Mautic\\CoreBundle\\Entity\\CommonRepository->saveEntity(Object(Mautic\\EmailBundle\\Entity\\Stat))
#11 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(372): Mautic\\EmailBundle\\Stat\\StatHelper->storeStat(Object(Mautic\\EmailBundle\\Entity\\Stat), 'JeremyJNewell@f...')
#12 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(422): Mautic\\EmailBundle\\Model\\SendEmailToContact->createContactStatEntry('JeremyJNewell@f...')
#13 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(222): Mautic\\EmailBundle\\Model\\SendEmailToContact->sendStandardEmail()
#14 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1505): Mautic\\EmailBundle\\Model\\SendEmailToContact->send()
#15 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1136): Mautic\\EmailBundle\\Model\\EmailModel->sendEmail(Object(Mautic\\EmailBundle\\Entity\\Email), Array, Array)
#16 /var/www/html/app/bundles/EmailBundle/Controller/AjaxController.php(59): Mautic\\EmailBundle\\Model\\EmailModel->sendEmailToLists(Object(Mautic\\EmailBundle\\Entity\\Email), Object(Doctrine\\ORM\\PersistentCollection), 92)
#17 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(127): Mautic\\EmailBundle\\Controller\\AjaxController->sendBatchAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'email')
#18 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('sendBatch', Object(Symfony\\Component\\HttpFoundation\\Request), 'email')
#19 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#20 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(96): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#21 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(105): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->forward('Mautic\\\\EmailBun...', Array)
#22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#23 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#24 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#28 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#29 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#30 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#32 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#33 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#34 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#35 {main}
"} {"hostname":"mautic-web","pid":2478}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Keep open

**Comment by simonai1254** [comment]
I found this related link here, might be interesting: https://forum.mautic.org/t/mautic-general-error-1467-failed-to-read-auto-increment-value-from-storage-engine/20861/3
