### ISSUE TITLE
Hubspot API Carregando... Erro interno do servidor 500 Mautic 4.4.5

### ISSUE THREAD

**Issue by Fagner-lourenco** [mautic/mautic#11925]
### Mautic Version

4.4.x series

### PHP version

7.4

### What happened?

BUG de integração

### How can we reproduce this issue?

Ao tentar atualizar a key API

### Relevant log output

```shell
[2023-02-05 03:34:41] mautic.ERROR: INTEGRATION ERROR: Hubspot - The API key provided is invalid. View or manage your API key here: https://app.hubspot.com/l/api-key/ [] {"hostname":"web154","pid":42870}
[2023-02-05 03:34:41] mautic.ERROR: Mautic\PluginBundle\Exception\ApiErrorException: The API key provided is invalid. View or manage your API key here: https://app.hubspot.com/l/api-key/ in /home/intellektbrasil/info/plugins/MauticCrmBundle/Api/HubspotApi.php:39 Stack trace: #0 /home/intellektbrasil/info/plugins/MauticCrmBundle/Api/HubspotApi.php(61): MauticPlugin\MauticCrmBundle\Api\HubspotApi->request() #1 /home/intellektbrasil/info/plugins/MauticCrmBundle/Integration/HubspotIntegration.php(236): MauticPlugin\MauticCrmBundle\Api\HubspotApi->getLeadFields() #2 /home/intellektbrasil/info/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php(479): MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration->getAvailableLeadFields() #3 /home/intellektbrasil/info/plugins/MauticCrmBundle/Integration/HubspotIntegration.php(202): MauticPlugin\MauticCrmBundle\Integration\CrmAbstractIntegration->getFormFieldsByObject() #4 /home/intellektbrasil/info/app/bundles/PluginBundle/Form/Type/FeatureSettingsType.php(70): MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration->getFormLeadFields() #5 /home/intellektbrasil/info/app/bundles/PluginBundle/Form/Type/FeatureSettingsType.php(146): Mautic\PluginBundle\Form\Type\FeatureSettingsType->Mautic\PluginBundle\Form\Type\{closure}() #6 /home/intellektbrasil/info/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\PluginBundle\Form\Type\FeatureSettingsType->Mautic\PluginBundle\Form\Type\{closure}() #7 /home/intellektbrasil/info/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #8 /home/intellektbrasil/info/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #9 /home/intellektbrasil/info/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #10 /home/intellektbrasil/info/vendor/symfony/form/Form.php(353): Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch() #11 /home/intellektbrasil/info/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php(51): Symfony\Component\Form\Form->setData() #12 /home/intellektbrasil/info/vendor/symfony/form/Form.php(389): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms() #13 /home/intellektbrasil/info/vendor/symfony/form/Form.php(493): Symfony\Component\Form\Form->setData() #14 /home/intellektbrasil/info/vendor/symfony/form/FormBuilder.php(208): Symfony\Component\Form\Form->initialize() #15 /home/intellektbrasil/info/vendor/symfony/form/FormFactory.php(32): Symfony\Component\Form\FormBuilder->getForm() #16 /home/intellektbrasil/info/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(324): Symfony\Component\Form\FormFactory->create() #17 /home/intellektbrasil/info/app/bundles/PluginBundle/Controller/PluginController.php(183): Symfony\Bundle\FrameworkBundle\Controller\Controller->createForm() #18 /home/intellektbrasil/info/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\PluginBundle\Controller\PluginController->configAction() #19 /home/intellektbrasil/info/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #20 /home/intellektbrasil/info/vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle() #21 /home/intellektbrasil/info/app/AppKernel.php(115): Symfony\Component\HttpKernel\Kernel->handle() #22 /home/intellektbrasil/info/app/middlewares/CORSMiddleware.php(82): AppKernel->handle() #23 /home/intellektbrasil/info/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\Middleware\CORSMiddleware->handle() #24 /home/intellektbrasil/info/app/middlewares/VersionCheckMiddleware.php(58): Mautic\Middleware\CatchExceptionMiddleware->handle() #25 /home/intellektbrasil/info/app/middlewares/TrustMiddleware.php(42): Mautic\Middleware\VersionCheckMiddleware->handle() #26 /home/intellektbrasil/info/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle() #27 /home/intellektbrasil/info/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle() #28 /home/intellektbrasil/info/index.php(24): Stack\run() #29 {main} [] {"hostname":"web154","pid":42870}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Please update to the latest version of Mautic, and update your Hubspot key to use the new format.

See the links in the release notes:

https://github.com/mautic/mautic/releases/tag/4.4.5.
