### ISSUE TITLE
Streamhandler 

### ISSUE THREAD

**Issue by CLAVALCOLLECTION2** [mautic/mautic#12196]
### Mautic Version

5.0.x series

### PHP version

Php108

### What browsers are you seeing the problem on?

Chrome

### What happened?

Streamhandler doesn't function so help me out 

### How can we reproduce this issue?

Step 1: Buy sending a code

### Relevant log output

```shell
at StreamHandler->write(array('message' => 'UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2023-04-11 05:09:06] local.ERROR: UnexpectedValueException: The stream or file "/var/www/instaweb/storage/logs/laravel-2023-04-11.log" could not be opened: failed to open stream: Permission denied in /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108Stack trace:#0 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)#2 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#3 /var/www/instaweb/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#4 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#5 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#6 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#7 /var/www/instaweb/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/instaweb/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/instaweb/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main} '))
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

It looks like this is a file/folder permissions issue. Check the docs here: https://docs.mautic.org/en/troubleshooting/file-ownership-and-permissions.

Please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
