### ISSUE TITLE
mautic:plugins:reload seems to be broken on 5.x

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12465]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When trying to test a PR, on installation a bunch of errors are thrown when it attempts to load plugins.

### How can we reproduce this issue?

Step 1: Fire up Gitpod on the 5.x branch
Step 2: Let it do its thing.

```
Enabling plugins...
PHP Deprecated:  Return type of SendGrid\ReplyTo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 77

Deprecated: Return type of SendGrid\ReplyTo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 77
PHP Deprecated:  Return type of SendGrid\ClickTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 116

Deprecated: Return type of SendGrid\ClickTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 116
PHP Deprecated:  Return type of SendGrid\OpenTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 155

Deprecated: Return type of SendGrid\OpenTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 155
PHP Deprecated:  Return type of SendGrid\SubscriptionTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 216

Deprecated: Return type of SendGrid\SubscriptionTracking::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 216
PHP Deprecated:  Return type of SendGrid\Ganalytics::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 301

Deprecated: Return type of SendGrid\Ganalytics::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 301
PHP Deprecated:  Return type of SendGrid\TrackingSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 366

Deprecated: Return type of SendGrid\TrackingSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 366
PHP Deprecated:  Return type of SendGrid\BccSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 407

Deprecated: Return type of SendGrid\BccSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 407
PHP Deprecated:  Return type of SendGrid\BypassListManagement::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 435

Deprecated: Return type of SendGrid\BypassListManagement::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 435
PHP Deprecated:  Return type of SendGrid\Footer::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 484

Deprecated: Return type of SendGrid\Footer::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 484
PHP Deprecated:  Return type of SendGrid\SandBoxMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 512

Deprecated: Return type of SendGrid\SandBoxMode::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 512
PHP Deprecated:  Return type of SendGrid\SpamCheck::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 561

Deprecated: Return type of SendGrid\SpamCheck::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 561
PHP Deprecated:  Return type of SendGrid\MailSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 634

Deprecated: Return type of SendGrid\MailSettings::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 634
PHP Deprecated:  Return type of SendGrid\ASM::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 676

Deprecated: Return type of SendGrid\ASM::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 676
PHP Deprecated:  Return type of SendGrid\Attachment::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 748

Deprecated: Return type of SendGrid\Attachment::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 748
PHP Deprecated:  Return type of SendGrid\Content::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 808

Deprecated: Return type of SendGrid\Content::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 808
PHP Deprecated:  Return type of SendGrid\Personalization::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 913

Deprecated: Return type of SendGrid\Personalization::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 913
PHP Deprecated:  Return type of SendGrid\Email::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 992

Deprecated: Return type of SendGrid\Email::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 992
PHP Deprecated:  Return type of SendGrid\Mail::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 1213

Deprecated: Return type of SendGrid\Mail::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 1213
PHP Deprecated:  Return type of SendGrid\Recipient::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/contacts/Recipients.php on line 73

Deprecated: Return type of SendGrid\Recipient::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/sendgrid/sendgrid/lib/helpers/contacts/Recipients.php on line 73
PHP Deprecated:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/app/bundles/CoreBundle/Twig/Helper/AssetsHelper.php on line 718

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/app/bundles/CoreBundle/Twig/Helper/AssetsHelper.php on line 718

In ExceptionConverter.php line 49:
                                                                                                                                       
  An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.plugins' doesn't exist  
                                                                                                                                       

In Exception.php line 28:
                                                                                        
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.plugins' doesn't exist  
                                                                                        

In Connection.php line 70:
                                                                                        
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.plugins' doesn't exist  
```

### Relevant log output

```shell
[2023-06-11 17:17:21] mautic.WARNING: Command `mautic:install` exited with status code -1 [] {"hostname":"mautic-web","pid":3418}
[2023-06-11 17:17:25] mautic.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.plugins' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 49 while running console command `mautic:plugins:reload` [stack trace] #0 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1935): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #1 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1878): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #2 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1103): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT p0_.id A...', Array, Array) #3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery('SELECT p0_.id A...', Array, Array, NULL) #4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Mautic\CoreBundle\Doctrine\Connection\ConnectionWrapper), Array, Array) #5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1212): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1166): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1) #7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(901): Doctrine\ORM\AbstractQuery->execute(NULL, 1) #8 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(388): Doctrine\ORM\AbstractQuery->getResult(1) #9 /var/www/html/app/bundles/PluginBundle/Entity/PluginRepository.php(42): Mautic\CoreBundle\Entity\CommonRepository->getEntities(Array) #10 /var/www/html/app/bundles/CoreBundle/Model/AbstractCommonModel.php(173): Mautic\PluginBundle\Entity\PluginRepository->getEntities(Array) #11 /var/www/html/app/bundles/PluginBundle/Model/PluginModel.php(103): Mautic\CoreBundle\Model\AbstractCommonModel->getEntities(Array) #12 /var/www/html/app/bundles/PluginBundle/Facade/ReloadFacade.php(34): Mautic\PluginBundle\Model\PluginModel->getInstalledPlugins() #13 /var/www/html/app/bundles/PluginBundle/Command/ReloadCommand.php(37): Mautic\PluginBundle\Facade\ReloadFacade->reloadPlugins() #14 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\PluginBundle\Command\ReloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\ReloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\ReloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 /var/www/html/bin/console(13): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #21 {main} [] {"hostname":"mautic-web","pid":3424}
[2023-06-11 17:17:25] mautic.WARNING: Command `mautic:plugins:reload` exited with status code 255 [] {"hostname":"mautic-web","pid":3424}
[2023-06-11 17:17:26] mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "/var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php" at line 576." at /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 145 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php\" at line 576. at /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:145)"} {"hostname":"mautic-web","pid":2075}
[2023-06-11 17:17:27] mautic.CRITICAL: Exception thrown when handling an exception (Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Failed to start the session because headers have already been sent by "/var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php" at line 576."). at /var/www/html/app/bundles/CoreBundle/Resources/views/Default/script.html.twig line 7) {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Failed to start the session because headers have already been sent by \"/var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php\" at line 576.\"). at /var/www/html/app/bundles/CoreBundle/Resources/views/Default/script.html.twig:7, RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php\" at line 576. at /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:145)"} {"hostname":"mautic-web","pid":2075}
[2023-06-11 17:17:27] mautic.ERROR: Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Failed to start the session because headers have already been sent by "/var/www/html/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php" at line 576."). - in file /var/www/html/app/bundles/CoreBundle/Resources/views/Default/script.html.twig - at line 7 [] {"hostname":"mautic-web","pid":2075}
[2023-06-11 17:19:53] mautic.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.plugins' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 49 while running console command `mautic:plugins:reload` [stack trace] #0 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1935): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #1 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1878): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #2 /var/www/html/vendor/doctrine/dbal/src/Connection.php(1103): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT p0_.id A...', Array, Array) #3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery('SELECT p0_.id A...', Array, Array, NULL) #4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Mautic\CoreBundle\Doctrine\Connection\ConnectionWrapper), Array, Array) #5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1212): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1166): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1) #7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(901): Doctrine\ORM\AbstractQuery->execute(NULL, 1) #8 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(388): Doctrine\ORM\AbstractQuery->getResult(1) #9 /var/www/html/app/bundles/PluginBundle/Entity/PluginRepository.php(42): Mautic\CoreBundle\Entity\CommonRepository->getEntities(Array) #10 /var/www/html/app/bundles/CoreBundle/Model/AbstractCommonModel.php(173): Mautic\PluginBundle\Entity\PluginRepository->getEntities(Array) #11 /var/www/html/app/bundles/PluginBundle/Model/PluginModel.php(103): Mautic\CoreBundle\Model\AbstractCommonModel->getEntities(Array) #12 /var/www/html/app/bundles/PluginBundle/Facade/ReloadFacade.php(34): Mautic\PluginBundle\Model\PluginModel->getInstalledPlugins() #13 /var/www/html/app/bundles/PluginBundle/Command/ReloadCommand.php(37): Mautic\PluginBundle\Facade\ReloadFacade->reloadPlugins() #14 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\PluginBundle\Command\ReloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\ReloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\ReloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 /var/www/html/bin/console(13): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #21 {main} [] {"hostname":"mautic-web","pid":3466}
[2023-06-11 17:19:53] mautic.WARNING: Command `mautic:plugins:reload` exited with status code 255 [] {"hostname":"mautic-web","pid":3466}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment]
@RCheesley see #12467
If you can see a working Mautic in Gitpod / DDEV, than that was the fix for this issue :)
