### ISSUE TITLE
Error "no component or dynamic content item" on grapesjsbuilder editor

### ISSUE THREAD

**Issue by mhdhamouday** [mautic/mautic#12712]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I create a new email and add dynamic content, then enter edit mode and click 'save', I encounter the error: 'no component or dynamic content item'. This issue began after I deactivated and then reactivated the grapesjsbuilder plugin. 

FYI: I've cleared the cache in the browser, removed contents from var/cache, and executed the /bin/console cache:clear command.

### How can we reproduce this issue?

Step 1:  create a new email
Step 2: add dynamic content
Step 3: enter edit mode and click 'save'

### Relevant log output

```shell
JS console:
backbone.js:370 TypeError: Cannot read properties of undefined (reading 'destroy')
    at e.customRte.e.customRte.disable (builder.service.js:296:13)
    at Object.disable (index.js:328:19)
    at ComponentTextView.js:73:19
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at n (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>) {level: 'error'}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, can you be specific what version of Mautic you're using, and which email template?

**Comment by mhdhamouday** [comment]
@RCheesley Version: 4.4.10
email template: "Confirm me"
![image](https://github.com/mautic/mautic/assets/16991900/bb1fb78b-eb72-494a-b803-ee4fdd8474dd)

**Comment by RCheesley** [comment]
Can you try and enter the following command:

`bin/console m:a:g`

Then clear your cache **and your browser cache**.

Let us know if that helps?

**Comment by mhdhamouday** [comment]
@RCheesley, thank you, but the issue remains the same.

**Comment by RCheesley** [comment]
Okay thanks for testing and getting back to us!  When you said that you deactivated and reactivated the plugin, could you just explain how you did that, and did you run the command to reload the plugins?

**Comment by mhdhamouday** [comment]
@RCheesley , I went to the plugins page and opened the GrpesJs plugin, then deactivated it. After that, I ran 'php /bin/console cache:clear'. Then, I reactivated it and clicked on the 'install/upgrade plugins' button on the plugins page, followed by clearing the cache again.

**Comment by LordRembo** [comment]
Just wanna mention a similar was solved recently in 5.x
