### ISSUE TITLE
Sending queued messages fails for segment email

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13060]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Sending queued segment messages results in error.

The EntityManager detach method for the event should be called only when the Event object exists.
https://github.com/mautic/mautic/blob/ebfd67f61691f21f18408745e8742c1502cc3c1c/app/bundles/ChannelBundle/Model/MessageQueueModel.php#L183

### How can we reproduce this issue?

1. Set Frequency Rule in Mautic setting for 1 message per day
2. Send a marketing email to segment
3. Send a marketing email to segment again - it should be added to the message queue because of limit
4. After 24h trigger the command to send the queue `ddev exec php bin/console mautic:messages:send`

### Relevant log output

```shell
console.CRITICAL: Error thrown while running command "mautic:messages:send". Message: "EntityManager#detach() expects parameter 1 to be an entity object, NULL given." {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): EntityManager#detach() expects parameter 1 to be an entity object, NULL given. at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:189)
[stacktrace]
#0 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(732): Doctrine\\ORM\\ORMInvalidArgumentException::invalidObject('EntityManager#d...', NULL)
#1 /var/www/html/app/bundles/ChannelBundle/Model/MessageQueueModel.php(204): Doctrine\\ORM\\EntityManager->detach(NULL)
#2 /var/www/html/app/bundles/ChannelBundle/Command/ProcessMarketingMessagesQueueCommand.php(69): Mautic\\ChannelBundle\\Model\\MessageQueueModel->sendMessages(NULL, NULL)
#3 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\\ChannelBundle\\Command\\ProcessMarketingMessagesQueueCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\\Component\\Console\\Application->doRunCommand(Object(Mautic\\ChannelBundle\\Command\\ProcessMarketingMessagesQueueCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand(Object(Mautic\\ChannelBundle\\Command\\ProcessMarketingMessagesQueueCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /var/www/html/bin/console(16): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 {main}
","command":"mautic:messages:send","message":"EntityManager#detach() expects parameter 1 to be an entity object, NULL given."} {"hostname":"mautic-web","pid":3497}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by patrykgruszka** [comment]
Fixed by #13071
