### ISSUE TITLE
Exception: cannot assign null to property while sending email to segment

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13093]
### Mautic Version

5.0.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I've got an error while executing command: `ddev exec php bin/console m:b:s` on latest 5.x (rc2) and 5.1 branches.

### How can we reproduce this issue?

* Run `ddev exec php bin/console m:b:s` - Cannot assign `null` to  `$limit`
* Run `ddev exec php bin/console m:b:s -l 1` - Cannot assign `null` to `$batch`

### Relevant log output

```shell
ERROR     [mautic] TypeError: Cannot assign null to property Mautic\ChannelBundle\Event\ChannelBroadcastEvent::$batch of type int (uncaught exception) at /var/www/html/app/bundles/ChannelBundle/Event/ChannelBroadcastEvent.php line 173 while running console command `mautic:broadcasts:send`
[stack trace]
#0 /var/www/html/app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php(110): Mautic\ChannelBundle\Event\ChannelBroadcastEvent->setBatch(NULL)
#1 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\ChannelBundle\Command\SendChannelBroadcastCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\ChannelBundle\Command\SendChannelBroadcastCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\ChannelBundle\Command\SendChannelBroadcastCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main} ["hostname" => "mautic-web","pid" => 1819]

ERROR     [mautic] TypeError: Cannot assign null to property Mautic\ChannelBundle\Event\ChannelBroadcastEvent::$limit of type int (uncaught exception) at /var/www/html/app/bundles/ChannelBundle/Event/ChannelBroadcastEvent.php line 160 while running console command `mautic:broadcasts:send`
[stack trace]
#0 /var/www/html/app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php(109): Mautic\ChannelBundle\Event\ChannelBroadcastEvent->setLimit(NULL)
#1 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\ChannelBundle\Command\SendChannelBroadcastCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\ChannelBundle\Command\SendChannelBroadcastCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\ChannelBundle\Command\SendChannelBroadcastCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main} ["hostname" => "mautic-web","pid" => 1784]
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Ready to test: https://github.com/mautic/mautic/pull/13172
