### ISSUE TITLE
Error thrown when processing a campaign in 5.1

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13106]
### Mautic Version

5.0.x series

### PHP version

8

### What happened?

When sending a campaign with a transactional mail send involved the following appears in the output:

```
gitpod /workspace/mautic (DPMMA-2537_oneclick-unsubscribe) $ ddev exec bin/console m:c:t
Triggering events for campaign 1
Triggering events for newly added contacts
8 total events(s) to be processed in batches of 100 contacts
 8/8 [============================] 100%
In EmojiHelper.php line 23:
                                                                                                                                                                                               
  Mautic\CoreBundle\Helper\EmojiHelper::toEmoji(): Argument #1 ($text) must be of type string, null given, called in /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php on line 1311  
                                                                                                                                                                                               

mautic:campaigns:trigger [-i|--campaign-id [CAMPAIGN-ID]] [--campaign-limit [CAMPAIGN-LIMIT]] [--contact-id [CONTACT-ID]] [--contact-ids [CONTACT-IDS]] [--min-contact-id [MIN-CONTACT-ID]] [--max-contact-id [MAX-CONTACT-ID]] [--thread-id [THREAD-ID]] [--max-threads [MAX-THREADS]] [--kickoff-only] [--scheduled-only] [--inactive-only] [-l|--batch-limit [BATCH-LIMIT]] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-f|--force]

Failed to execute command bin/console m:c:t: exit status 255
```

### How can we reproduce this issue?

Step 1: Create a campaign with a send email (transactional) and use the default one called 'Email test'
Step 2: Rebuild (ddev exec bin/console m:c:r) and then trigger (ddev exec bin/console m:c:t) campaigns
Step 3: Check the output

### Relevant log output

```shell
[2023-12-22 13:39:21] mautic.ERROR: TypeError: Mautic\CoreBundle\Helper\EmojiHelper::toEmoji(): Argument #1 ($text) must be of type string, null given, called in /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php on line 1311 (uncaught exception) at /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php line 23 while running console command `mautic:campaigns:trigger` [stack trace] #0 /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php(1311): Mautic\CoreBundle\Helper\EmojiHelper::toEmoji(NULL, 'short') #1 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(121): Mautic\EmailBundle\Helper\MailHelper->setEmail(Object(Mautic\EmailBundle\Entity\Email), true, Array, Array) #2 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1424): Mautic\EmailBundle\Model\SendEmailToContact->setEmail(Object(Mautic\EmailBundle\Entity\Email), Array, Array, Array, 'transactional') #3 /var/www/html/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php(297): Mautic\EmailBundle\Model\EmailModel->sendEmail(Object(Mautic\EmailBundle\Entity\Email), Array, Array) #4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Mautic\EmailBundle\EventListener\CampaignSubscriber->onCampaignTriggerActionSendEmailToContact(Object(Mautic\CampaignBundle\Event\PendingEvent), 'mautic.email.on...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Mautic\CampaignBundle\Event\PendingEvent), 'mautic.email.on...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'mautic.email.on...', Object(Mautic\CampaignBundle\Event\PendingEvent)) #7 /var/www/html/app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php(47): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Mautic\CampaignBundle\Event\PendingEvent), 'mautic.email.on...') #8 /var/www/html/app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php(46): Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection)) #9 /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php(129): Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection)) #10 /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php(100): Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter)) #11 /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php(171): Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter), false) #12 /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(159): Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter)) #13 /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(60): Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent() #14 /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(311): Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute(Object(Mautic\CampaignBundle\Entity\Campaign), Object(Mautic\CampaignBundle\Executioner\ContactFinder\Limiter\ContactLimiter), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(264): Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff() #16 /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(213): Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign(Object(Mautic\CampaignBundle\Entity\Campaign)) #17 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #21 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #22 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #23 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #24 {main} [] {"hostname":"mautic-web","pid":4195}
[2023-12-22 13:39:21] mautic.WARNING: Command `mautic:campaigns:trigger` exited with status code 1 [] {"hostname":"mautic-web","pid":4195}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team!

**Comment by RCheesley** [comment]
Note: This also happens when I am selecting the same email to send directly to a contact. In the background this error is thrown:

`[2023-12-22 13:43:23] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\CoreBundle\Helper\EmojiHelper::toEmoji(): Argument #1 ($text) must be of type string, null given, called in /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php on line 1311" at /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php line 23 {"exception":"[object] (TypeError(code: 0): Mautic\\CoreBundle\\Helper\\EmojiHelper::toEmoji(): Argument #1 ($text) must be of type string, null given, called in /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php on line 1311 at /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php:23)"} {"hostname":"mautic-web","pid":2167}`

**Comment by escopecz** [comment]
I bet the same issue is in 5.x. I'll change the milestone. We have to look into this before the GA release.

**Comment by mollux** [comment]
@RCheesley 

I can't reproduce this, but I can see a potential problem in the code

can you share a screenshot of the email itself? both i edit mode and builder mode?

**Comment by RCheesley** [comment]
You need to load the fixtures using bin/console d:f:l and use the email that's present from the fixtures.

**Comment by mollux** [comment]
@RCheesley found the issue, it's actually related to the email itself, not to logic in Mautic itself. It's the fixture that's wrong.

I'l create a PR to fix this
