### ISSUE TITLE
Bulk Export | Bulk export email never arrives

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#13540]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Email containing link to download bulk export does not arrive.
I have tried this on multiple instances with the same result. 

### How can we reproduce this issue?

1. Select segment with contacts
2. Select "Export to CSV"
3. Wait for email to arrive, it does not

### Relevant log output

```shell
No logs are produced at the time the button is pressed. 

However, This comes up: 

[2024-03-12T12:16:06.599668+00:00] mautic.ERROR: Symfony\Component\Messenger\Exception\InvalidArgumentException: You cannot receive messages from the Messenger SyncTransport. (uncaught exception) at /var/www/mautic/vendor/symfony/messenger/Transport/Sync/SyncTransport.php line 37 while running console command `messenger:consume` [stack trace] #0 /var/www/mautic/vendor/symfony/messenger/Worker.php(101): Symfony\Component\Messenger\Transport\Sync\SyncTransport->get() #1 /var/www/mautic/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(234): Symfony\Component\Messenger\Worker->run() #2 /var/www/mautic/vendor/symfony/console/Command/Command.php(298): Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() #3 /var/www/mautic/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run() #4 /var/www/mautic/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand() #5 /var/www/mautic/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #6 /var/www/mautic/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun() #7 /var/www/mautic/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #8 /var/www/mautic/bin/console(16): Symfony\Component\Console\Application->run() #9 {main} [] {"hostname":"HOSTNAME","pid":397952}
[2024-03-12T12:16:06.601338+00:00] mautic.WARNING: Command `messenger:consume` exited with status code 1 [] {"hostname":"HOSTNAME","pid":397952}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by vexersa** [comment]
Here's my associated Mautic forum thread: https://forum.mautic.org/t/bulk-contact-export-email-does-not-arrive/31169/11

**Comment by vexersa** [comment]
I notice that the error log is referencing a path which is not where my Mautic instance is located:

/var/www/mautic/vendor/symfony/messenger/Worker.php

This file doesn't exist on my system at that location. Can this be manually changed?

**Comment by vexersa** [comment]
I have tested exporting through other menus and if you click the blue drop down in the menu above the checkbox multi select options next to contacts, say in a segment: 

![image](https://github.com/mautic/mautic/assets/7994227/efa8aad5-16fb-4d56-854a-31d3ae524fff)

And then select: 
![image](https://github.com/mautic/mautic/assets/7994227/69ffe5c6-1a69-4fe0-89ff-e94a6cb25c35)
Export to Excel

The file is made available for download as it used to in Mautic 4. A save file dialog is presented. 

No other export functions work and the notice that the export has been queued and email will be sent is displayed. 

No email arrives.

**Comment by vexersa** [comment]
Update:
Attempting to export a database of 500k contacts has failed with the above "Export to Excel" option which usually generates a .xlsx file for download.

**Comment by stefanomarty** [comment]
> Here's my associated Mautic forum thread: https://forum.mautic.org/t/bulk-contact-export-email-does-not-arrive/31169/11

I posted a reply in your forum thread.

**Comment by RCheesley** [comment]
Closing this given the conversations happened over in the forum which is the appropriate place. Thanks folks! :)
