### ISSUE TITLE
Mautic Dashboard and JavaScript loading Issue

### ISSUE THREAD

**Issue by abouzia** [mautic/mautic#13575]
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.0,8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I installed Mautic from App installer in CyberPanel. However, upon accessing the Mautic dashboard, it continuously loads, and the side menu expanded items are not functional, indicating that JavaScript is not loading properly. 
Initially, I suspected that the issue might be related to the Cloudflare proxy, but even after disabling the proxy, the problem persists.
I will include the browser console logs for reference.
![Screenshot 2024-03-23 024244](https://github.com/mautic/mautic/assets/2650972/190d583b-651c-4f9e-8ab5-03285cf0e665)

### How can we reproduce this issue?

Step 1: Install Mautic using the App installer in CyberPanel.
Step 2: Access the Mautic dashboard.

### Relevant log output

```shell
Uncaught SyntaxError: Invalid regular expression flags
app.js:1  Uncaught ReferenceError: jQuery is not defined
    at app.js:1:30
ckeditor.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
dashboard:85  Uncaught TypeError: Cannot set properties of undefined (setting 'getActiveBuilderName')
    at dashboard:85:37
builder.js?va9855a20:1  Uncaught TypeError: Cannot set properties of undefined (setting 'launchBuilder')
    at parcelRequire.RfSX../asset.service (builder.js:178:8)
    at f (builder.js?va9855a20:1:468)
    at parcelRequire.iHk9 (builder.js?va9855a20:1:771)
    at builder.js?va9855a20:1:1023
dashboard:1312  Uncaught TypeError: Cannot read properties of undefined (reading 'onPageLoad')
    at dashboard:1312:24
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by abouzia** [comment]
![Screenshot 2024-03-23 024430](https://github.com/mautic/mautic/assets/2650972/53bc2694-ddb6-4f31-b880-103d6f8e1785)

**Comment by abouzia** [comment]
https://github.com/usmannasir/cyberpanel/issues/1226
