### ISSUE TITLE
Emoji causes 500 internal server error when saving email template

### ISSUE THREAD

**Issue by djiworks** [mautic/mautic#14068]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

PHP 8.1.29 (cli) (built: Jun 13 2024 03:04:20) (NTS)

### What browsers are you seeing the problem on?

Safari

### What happened?

Docker compose file :
```version: "3.9"

services:
  database:
    image: mariadb:latest #(mariadb from 11.4.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper-)
    container_name: mautic-db
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql:rw
    restart: always
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: mautic/mautic:5.1-apache
    volumes:
      - mautic_data:/var/www/html:rw
    environment:
      - MAUTIC_DB_HOST=
      - MAUTIC_DB_USER=
      - MAUTIC_DB_PASSWORD=
      - MAUTIC_DB_NAME=
      - MAUTIC_RUN_CRON_JOBS=true
    restart: always
    depends_on:
      - database
    links:
      - database
    networks:
      - mauticnet
    ports:
      - "80:80"

networks:
  mauticnet:

volumes:
  database:
  mautic_data:
```
Here the `/var/www/html/docroot/app/config/config.php` file
```php
...
// Doctrine Configuration
$connectionSettings = [
    'driver'                => '%mautic.db_driver%',
    'host'                  => '%mautic.db_host%',
    'port'                  => '%mautic.db_port%',
    'dbname'                => '%mautic.db_name%',
    'user'                  => '%mautic.db_user%',
    'password'              => '%mautic.db_password%',
    'charset'               => 'utf8mb4',
    'default_table_options' => [
        'charset'    => 'utf8mb4',
        'collate'    => 'utf8mb4_unicode_ci',
        'row_format' => 'DYNAMIC',
    ],
...
if (!empty($localConfigParameterBag->get('db_host_ro'))) {
    $connectionSettings['wrapper_class']   = Mautic\CoreBundle\Doctrine\Connection\PrimaryReadReplicaConnectionWrapper::class;
    $connectionSettings['keep_replica']    = true;
    $connectionSettings['replicas']        = [
        'replica1' => [
            'host'                  => '%mautic.db_host_ro%',
            'port'                  => '%mautic.db_port%',
            'dbname'                => '%mautic.db_name%',
            'user'                  => '%mautic.db_user%',
            'password'              => '%mautic.db_password%',
            'charset'               => 'utf8mb4',
	    'default_table_options' => [
        	'charset'    => 'utf8mb4',
        	'collate'    => 'utf8mb4_unicode_ci',
        	'row_format' => 'DYNAMIC',
    	     ]
        ],
    ];
}

```
I did all the tricks from here : https://github.com/mautic/mautic/issues/6490#issuecomment-420041223
Except the change into /etc/my.cnf (because it's not mentioned where to find the file and I didn't find it on MariaDB instance)

Here what my db says and everything is `utf8mb4_unicode_ci`and `utf8mb4 ` :
```
MariaDB [mautic51]> select COLUMN_NAME, CHARACTER_SET_NAME, COLLATION_NAME, COLUMN_TYPE from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='emails';
+-----------------------+--------------------+--------------------+------------------+
| COLUMN_NAME           | CHARACTER_SET_NAME | COLLATION_NAME     | COLUMN_TYPE      |
+-----------------------+--------------------+--------------------+------------------+
| id                    | NULL               | NULL               | int(10) unsigned |
| category_id           | NULL               | NULL               | int(10) unsigned |
| translation_parent_id | NULL               | NULL               | int(10) unsigned |
| variant_parent_id     | NULL               | NULL               | int(10) unsigned |
| unsubscribeform_id    | NULL               | NULL               | int(10) unsigned |
| preference_center_id  | NULL               | NULL               | int(10) unsigned |
| is_published          | NULL               | NULL               | tinyint(1)       |
| date_added            | NULL               | NULL               | datetime         |
| created_by            | NULL               | NULL               | int(11)          |
| created_by_user       | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| date_modified         | NULL               | NULL               | datetime         |
| modified_by           | NULL               | NULL               | int(11)          |
| modified_by_user      | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| checked_out           | NULL               | NULL               | datetime         |
| checked_out_by        | NULL               | NULL               | int(11)          |
| checked_out_by_user   | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| name                  | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| description           | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| subject               | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| from_address          | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| from_name             | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| reply_to_address      | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| bcc_address           | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| use_owner_as_mailer   | NULL               | NULL               | tinyint(1)       |
| template              | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| content               | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| utm_tags              | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| plain_text            | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| custom_html           | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| email_type            | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| publish_up            | NULL               | NULL               | datetime         |
| publish_down          | NULL               | NULL               | datetime         |
| read_count            | NULL               | NULL               | int(11)          |
| sent_count            | NULL               | NULL               | int(11)          |
| variant_sent_count    | NULL               | NULL               | int(11)          |
| variant_read_count    | NULL               | NULL               | int(11)          |
| revision              | NULL               | NULL               | int(11)          |
| lang                  | utf8mb4            | utf8mb4_unicode_ci | varchar(191)     |
| variant_settings      | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| variant_start_date    | NULL               | NULL               | datetime         |
| dynamic_content       | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| headers               | utf8mb4            | utf8mb4_unicode_ci | longtext         |
| public_preview        | NULL               | NULL               | tinyint(1)       |
+-----------------------+--------------------+--------------------+------------------+
MariaDB [mautic51]> SHOW CREATE DATABASE mautic51
    -> ;
+----------+-------------------------------------------------------------------------------------------------+
| Database | Create Database                                                                                 |
+----------+-------------------------------------------------------------------------------------------------+
| mautic51 | CREATE DATABASE `mautic51` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ |
+----------+-------------------------------------------------------------------------------------------------+

MariaDB [mautic51]> SHOW VARIABLES LIKE 'character_set%';
+--------------------------+-------------------------------+
| Variable_name            | Value                         |
+--------------------------+-------------------------------+
| character_set_client     | utf8mb3                       |
| character_set_collations | utf8mb4=utf8mb4_uca1400_ai_ci |
| character_set_connection | utf8mb3                       |
| character_set_database   | utf8mb4                       |
| character_set_filesystem | binary                        |
| character_set_results    | utf8mb3                       |
| character_set_server     | utf8mb4                       |
| character_set_system     | utf8mb3                       |
| character_sets_dir       | /usr/share/mariadb/charsets/  |
+--------------------------+-------------------------------+
```
Emoji is ok for subject and name of the email. But it does not work for content of the email

### How can we reproduce this issue?

Step 1: Create or modify a new email type : template
Step 2 : open generator (text editor)
Step 3 : Add text component
Step 4 : type text and emojis
Step 5 : Save

### Relevant log output

```shell
"POST /s/emails/edit/16?mauticUserLastActive=&mauticLastNotificationId= HTTP/1.1" 500 1173 "[domain]/s/emails/edit/16" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @djiworks thanks for reporting this. Please can you check your logs in the var/logs folder within Mautic (or in the system info screen within the application) because the one you've shared above doesn't tell us about the stack trace/source of the error within the Mautic application. Thanks!

**Comment by djiworks** [comment]
Hi @RCheesley, thanks for replying. Finally after restarting containers, everything seems working for now.

**Comment by RCheesley** [comment]
Thanks for getting back to us @djiworks - much appreciated and glad you got it up and working again! The good old 'have you switched it off and on again' in full effect! 

![turning-it-off-and-on-again](https://github.com/user-attachments/assets/f72c429b-6de5-43f1-9d2e-48ed3c5568ea)

**Comment by djiworks** [comment]
FYI : it worked for a time, now same issue even if the containers was not restarted, nothing change on it. It means, restarting only fix issue for a while. No sense actually. And I don't have any log, just `500 internal server error`

only thing I get from log here `/var/www/html/var/logs` is a repetition (indefinitely) of this error line : 
```
[2024-09-11T07:38:02.975838+00:00] mautic.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: Command "mautic:emails:send" is not defined.  Did you mean one of these?     mautic:broadcasts:send     mautic:email:fetch     mautic:emails:fetch     mautic:messages:send (uncaught exception) at /var/www/html/vendor/symfony/console/Application.php line 720 while running console command `UNKNOWN` [stack trace] #0 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(116): Symfony\Component\Console\Application->find('mautic:emails:s...') #1 /var/www/html/vendor/symfony/console/Application.php(259): Symfony\Bundle\FrameworkBundle\Console\Application->find('mautic:emails:s...') #2 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #3 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 {main} [] {"hostname":"676045eecae5","pid":980469}
```

Can we get other logs anywhere else ? Is this due to a kind of production mode ?

**Comment by gcoli6** [comment]
Same problem here, but without container, just a bare metal installation. Someone with any clue why Mautic does that?
