### ISSUE TITLE
Sync Fails in SugarCRM Plugin if "update emails do not contact" enabled

### ISSUE THREAD

**Issue by pstevens71** [mautic/mautic#14111]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Sync Fails in SugarCRM Plugin if "update emails do not contact" enabled.

Error message:  Call to a member function getDoNotContact() on null

### How can we reproduce this issue?

Step 1: Setup Mautic/SugarCRM plugin for SuiteCRM
Step 2: enable the "update emails do not contact" feature
Step 3:  Run a sync job (either manually or in cron)
Step 4: Fails with error

### Relevant log output

```shell
[2024-09-12T21:41:46.297147+00:00] mautic.ERROR: Error: Call to a member function getDoNotContact() on null (uncaught exception) at xxxxxxxxxxxxxxxxx/app/bundles/LeadBundle/Model/DoNotContact.php line 33 while running console command `mautic:integration:fetchleads` [stack trace] 
#0 xxxxxxxxxxxxxxxxxxxxxxxx/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php(1370): Mautic\LeadBundle\Model\DoNotContact->removeDncForContact(0, 'email', true, 1) 

#1 xxxxxxxxxxxxxxxxxxxxxxxxx/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php(846): MauticPlugin\MauticCrmBundle\Integration\SugarcrmIntegration->fetchDncToMautic(Object(Mautic\LeadBundle\Entity\Lead), Array) 

#2 xxxxxxxxxxxxxxxxxxxxxxxx/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php(576): MauticPlugin\MauticCrmBundle\Integration\SugarcrmIntegration->amendLeadDataBeforeMauticPopulate(Array, 'Leads') 

#3 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/app/bundles/PluginBundle/Command/FetchLeadsCommand.php(152): MauticPlugin\MauticCrmBundle\Integration\SugarcrmIntegration->getLeads(Array, Array, NULL, Array, 'Leads') 

#4 xxxxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/console/Command/Command.php(298): Mautic\PluginBundle\Command\FetchLeadsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#5 xxxxxxxxxxxxxxxxx/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#6 xxxxxxxxxxxxxxxxxxx/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#7 /vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#8 xxxxxxxxxxxxxxxxxxxxxxx/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#9 xxxxxxxxxxxxx/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#10 xxxxxxxxxxxxxxxx/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 {main} [] {"hostname":"224.253.12.198.host.secureserver.net","pid":28293}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by pstevens71** [comment]
UPDATE****
With further testing, I had two lead records that were created by and API without the "do not contact" field in SuiteCRM being populated.  Thus the "null" value.  I deleted these two records and the sync proceeded as normal.  I think we can close this issue but it might be a good idea to test for this so that it doesn't crash the sync.   Something like:

if ($lead && method_exists($lead, 'getDoNotContact')) {
    // Proceed with DNC logic
}

**Comment by Oluwatos94** [comment]
Thank you @pstevens71  for the update! It's good to know that deleting the two records resolved the sync issue on your end. I haven't had a chance to test this yet, but your suggestion to check for the "do not contact" field before proceeding with the sync sounds like a practical solution.

I'll get someone to review and test this further, and if needed, we can look into implementing the validation to prevent similar issues. Let's keep the issue open for now until we confirm the fix. Thanks again for the thorough investigation!
