### ISSUE TITLE
Date selection ends in a HTTP 500 error

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#1971]
## Description
When I browse email stats for a mailing and try to select a different time range using the widget, Mautic responds with a HTTP 500 error.

[2016-07-07 11:28:20] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "isMysql" of class "Mautic\CoreBundle\Helper\Chart\ChartQuery"." at /vagrant/app/bundles/CoreBundle/Helper/Chart/ChartQuery.php line 299 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"isMysql\" of class \"Mautic\\CoreBundle\\Helper\\Chart\\ChartQuery\". at /vagrant/app/bundles/CoreBundle/Helper/Chart/ChartQuery.php:299)\n[stacktrace]\n#0 /vagrant/app/bundles/CoreBundle/Helper/Chart/ChartQuery.php(251): Mautic\\CoreBundle\\Helper\\Chart\\ChartQuery->completeTimeData(Array)\n#1 /vagrant/app/bundles/EmailBundle/Model/EmailModel.php(1496): Mautic\\CoreBundle\\Helper\\Chart\\ChartQuery->loadAndBuildTimeData(Object(Doctrine\\DBAL\\Query\\QueryBuilder))\n#2 /vagrant/app/bundles/EmailBundle/Model/EmailModel.php(758): Mautic\\EmailBundle\\Model\\EmailModel->getEmailsLineChartData(NULL, Object(DateTime), Object(DateTime), NULL, Array)\n#3 /vagrant/app/bundles/EmailBundle/Controller/EmailController.php(370): Mautic\\EmailBundle\\Model\\EmailModel->getEmailGeneralStats(Object(Mautic\\EmailBundle\\Entity\\Email), true, NULL, Object(DateTime), Object(DateTime))\n#4 /vagrant/app/bundles/CoreBundle/Controller/CommonController.php(367): Mautic\\EmailBundle\\Controller\\EmailController->viewAction('7', '')\n#5 [internal function]: Mautic\\CoreBundle\\Controller\\CommonController->executeAction('view', '7', 0, '')\n#6 /vagrant/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array)\n#7 /vagrant/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#8 /vagrant/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 /vagrant/vendor/symfony/http-kernel/Kernel.php(185): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#10 /vagrant/app/AppKernel.php(131): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#11 /vagrant/app/middlewares/CORSMiddleware.php(96): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#12 /vagrant/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#13 /vagrant/app/middlewares/Prod/SetMauticHeaderMiddleware.php(41): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#14 /vagrant/app/middlewares/VersionCheckMiddleware.php(56): Mautic\\Middleware\\Prod\\SetMauticHeaderMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#15 /vagrant/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /vagrant/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 /vagrant/index.php(30): Stack\\run(Object(Stack\\StackedHttpKernel))\n#18 {main}"} []

The isMysql function is not defined in either Mautic\CoreBundle\Helper\Chart\ChartQuery or Mautic\CoreBundle\Helper\Chart\AbstactChart. I think that commit accidentally removed the function: https://github.com/mautic/mautic/commit/172343628d182153d8f9c06234b2653c2fa2e218

**Comment by wittwerch** [comment]
@dbhurley do you mind if I can the title back to something meaningful? :)

**Comment by escopecz** [comment]
This error should be fixed by https://github.com/mautic/mautic/pull/1968 . If you could test that PR and comment bellow how the test went for you, it'd speed up the next release.
