### ISSUE TITLE
Custom date field in maleads set to all zeros causes error

### ISSUE THREAD

**Issue by mackina** [mautic/mautic#2767]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

We insert leads in the Mautic DB from our CRM (via a cron). We have a custom date field, and in some cases this is set to 0000-00-00. If we try to edit that lead we get an error page. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11 
| PHP version | PHP Version 7.0.8-3

### Steps to reproduce:
1.  Create a lead in the DB
2.  Set a custom date field to 0000-00-00
3. Go in to Mautic interface, view lead
4. Click edit button
5. Get error page
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Would you mind posting the error message? It's important information for a bug report.

**Comment by mackina** [comment]
Yes, should have been clearer. It's the 500 internal error one.

**Comment by escopecz** [comment]
That doesn't say much. What is in the logs? https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by mackina** [comment]
[2016-10-17 08:46:25] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "ujoin": Unexpected data found." at /var/www/html/nudgr.io/vendor/symfony/form/Form.php line 1086 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"ujoin\": Unexpected data found. at /var/www/html/nudgr.io/vendor/symfony/form/Form.php:1086, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unexpected data found. at /var/www/html/nudgr.io/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php:141)"} []

**Comment by robwent** [comment]
I can confirm this.

We have a birthday field which was getting '0000-00-00' set (for an unknown reason).

When trying to access the edit page for the contact it results in a 500 error.

    [2018-01-23 10:31:56] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "birthday": Unexpected data found." at /pathto/mautic/vendor/symfony/form/Form.php line 1098 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"birthday\": Unexpected data found. at /pathto/mautic/vendor/symfony/form/Form.php:1098, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unexpected data found. at /pathto/mautic/vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToStringTransformer.php:129)"} []

**Comment by jordan8037310** [comment]
This is still an active issue. Can we re-open it? 

While working via API, we got a 200 response updating a date field to a Unix Timestamp, and thereafter the contact record could no longer be edited. 

Perhaps this deserves a resolution? I'm guessing this issue persists to future versions. We're on 2.16.2.

**Comment by RCheesley** [comment]
As we are only providing fixes for 3.x going forward, can you please test on 3.0.1 and if it's still happening then we can re-open!

**Comment by jordan8037310** [comment]
Encountered #9000 and #9001 while trying to test this issue on Mautibox.com

**Comment by jordan8037310** [comment]
@RCheesley I tested this again on Mautibox.com

1. Created a new field of type `Date/Time` called `custom_date_time`
2. Create a contact
3. Enter `0000-00-00` into `custom_date_time` field
4. contact cannot be saved and closed.

Instead some validation error should be presented to the user. 

Also, I want to point out here that the API should be rejecting any input that is not a valid type, instead of corrupting the contact records. We were pushing `unix timestamps` and instead of getting an error, the data was being interpreted as years, months, days (even without date formatting validation).

I'm guessing some underlying date/time validation is missing for this field type.

Errors from the logs on Mautibox.com:

```
[2020-07-09 23:18:03] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes)" at /var/app/current/code/pulls/staging/vendor/symfony/debug/DebugClassLoader.php line 152 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) at /var/app/current/code/pulls/staging/vendor/symfony/debug/DebugClassLoader.php:152)
[stacktrace]
#0 {main}
"} 
[2020-07-09 23:18:07] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10489856 bytes)" at /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/DataCollector/DataCollector.php line 51 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10489856 bytes) at /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/DataCollector/DataCollector.php:51)
[stacktrace]
#0 {main}
"} 
[2020-07-09 23:18:07] mautic.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "/var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Response.php" at line 361. at /var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 150) {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Response.php\" at line 361. at /var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:150)
[stacktrace]
#0 /var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(323): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->start()
#1 /var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Session/Session.php(256): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->getBag('attributes')
#2 /var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Session/Session.php(280): Symfony\\Component\\HttpFoundation\\Session\\Session->getBag('attributes')
#3 /var/app/current/code/pulls/staging/vendor/symfony/http-foundation/Session/Session.php(73): Symfony\\Component\\HttpFoundation\\Session\\Session->getAttributeBag()
#4 /var/app/current/code/pulls/staging/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php(58): Symfony\\Component\\HttpFoundation\\Session\\Session->get('_timezone', 'UTC')
#5 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\\CoreBundle\\EventListener\\EnvironmentSubscriber->onKernelRequestSetTimezone(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#6 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#7 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#8 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#9 /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#10 /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#11 /var/app/current/code/pulls/staging/app/bundles/CoreBundle/EventListener/ExceptionListener.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2, false)
#12 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\\CoreBundle\\EventListener\\ExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#13 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#14 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#15 /var/app/current/code/pulls/staging/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#16 /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/HttpKernel.php(227): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#17 /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/HttpKernel.php(100): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Symfony\\Component\\Debug\\Exception\\OutOfMemoryException), Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#18 /var/app/current/code/pulls/staging/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(117): Symfony\\Component\\HttpKernel\\HttpKernel->terminateWithException(Object(Symfony\\Component\\Debug\\Exception\\OutOfMemoryException), Object(Symfony\\Component\\HttpFoundation\\Request))
#19 /var/app/current/code/pulls/staging/vendor/symfony/debug/ErrorHandler.php(601): Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::Symfony\\Component\\HttpKernel\\EventListener\\{closure}(Object(Symfony\\Component\\Debug\\Exception\\OutOfMemoryException))
#20 /var/app/current/code/pulls/staging/vendor/symfony/debug/ErrorHandler.php(692): Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(Symfony\\Component\\Debug\\Exception\\OutOfMemoryException), Array)
#21 [internal function]: Symfony\\Component\\Debug\\ErrorHandler::handleFatalError()
#22 {main}
"} 
```
