### ISSUE TITLE
Error upgrading 2.8.2

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#4197]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.9

### Steps to reproduce:
1. Upgrade from 2.8.1 to 2.8.2
2. My process is: merge in changes from new master branch release
3. Deploy staging branch with changes and run `composer install`.
4. Composer install fails with following error message:
 
### Log errors: 

```
[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Ar
  gument 1 passed to Mautic\PluginBundle\Helper\IntegrationHelper::__construct() must be an instan
  ce of Symfony\Component\HttpKernel\Kernel, instance of Mautic\CoreBundle\Factory\MauticFactory g
  iven, called in /var/www/vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php
   on line 10183 in /var/www/vhosts/mydomain.com/httpdocs/web/app/bundles/PluginBundle/Helper/
  IntegrationHelper.php:87
  Stack trace:
  #0 /var/www/vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php(10183): Maut
  ic\PluginBundle\Helper\IntegrationHelper->__construct(Object(Mautic\CoreBundle\Factory\MauticFac
  tory))
  #1 /var/www/vhosts/mydomain.com/httpdocs/web/vendor/symfony/dependency-injection/Container.p
  hp(314): appProdProjectContainer->getMautic_Helper_IntegrationService()
  #2 /var/www/vhosts/mydomain.com/httpdocs/web/plugins/MauticCitrixBundle/MauticCitrixBundle.p
  hp(26): Symfony\Component\DependencyInjection\Container->get( in /var/www/vhosts/obd.carcare.new
  s/httpdocs/web/app/bundles/PluginBundle/Helper/IntegrationHelper.php on line 87
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Error: Uncaugh
  t Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic
  \PluginBundle\Helper\IntegrationHelper::__construct() must be an instance of Symfony\Component\H
  ttpKernel\Kernel, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /var/www/
  vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php on line 10183 in /var/ww
  w/vhosts/mydomain.com/httpdocs/web/app/bundles/PluginBundle/Helper/IntegrationHelper.php:87
  Stack trace:
  #0 /var/www/vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php(10183): Maut
  ic\PluginBundle\Helper\IntegrationHelper->__construct(Object(Mautic\CoreBundle\Factory\MauticFac
  tory))
  #1 /var/www/vhosts/mydomain.com/httpdocs/web/vendor/symfony/dependency-injection/Container.p
  hp(314): appProdProjectContainer->getMautic_Helper_IntegrationService()
  #2 /var/www/vhosts/mydomain.com/httpdocs/web/plugins/MauticCitrixBundle/MauticCitr in /var/w
  ww/vhosts/mydomain.com/httpdocs/web/app/bundles/PluginBundle/Helper/IntegrationHelper.php on
   line 87
```

Ran into this issue while testing #3717

**Comment by escopecz** [comment]
Actually, it's a cache issue. Run `rm -rf app/cache/prod/*` and then `composer install`. Let us know if it helped or not. I'll close it for now since it helped my when I got this error.
