### ISSUE TITLE
2.10.1 import bug

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#5076]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Open Contact Modules
Click Import
Select CSV File
**Change delimeter to ";"**
Click Upload

Screen answer "can't read CSV file"

Reselect the same field, click upload

Error 500 is displayed on screen

If you try to go back to import, nothing happen, the wizard is not displayed anymore until you log out and log in back !

Seems the bug is only when delimeter is changed to ";" as it works great if we keep the standard "," delimeter

Here is a sample CSV file (encoded in UTF8 without BOM)
[Samplefile.txt](https://github.com/mautic/mautic/files/1349357/Samplefile.txt)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.12

### Log errors: 

the second error (error 500) : 
[2017-10-02 17:16:50] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "A form with an empty name cannot have a parent form." at /var/www/mautic/www_prod/vendor/symfony/form/Form.php line 273 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): A form with an empty name cannot have a parent form. at /var/www/mautic/www_prod/vendor/symfony/form/Form.php:273)\n[stacktrace]\n#0 /var/www/mautic/www_prod/vendor/symfony/form/Form.php(917): Symfony\\Component\\Form\\Form->setParent(Object(Symfony\\Component\\Form\\Form))\n#1 /var/www/mautic/www_prod/vendor/symfony/form/FormBuilder.php(221): Symfony\\Component\\Form\\Form->add(Object(Symfony\\Component\\Form\\Form))\n#2 /var/www/mautic/www_prod/vendor/symfony/form/FormFactory.php(40): Symfony\\Component\\Form\\FormBuilder->getForm()\n#3 /var/www/mautic/www_prod/app/bundles/LeadBundle/Controller/ImportController.php(215): Symfony\\Component\\Form\\FormFactory->create('lead_field_impo...', Array, Array)\n#4 /var/www/mautic/www_prod/app/bundles/CoreBundle/Controller/CommonController.php(475): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')\n#5 [internal function]: Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')\n#6 /var/www/mautic/www_prod/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Array, Array)\n#7 /var/www/mautic/www_prod/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#8 /var/www/mautic/www_prod/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 /var/www/mautic/www_prod/vendor/symfony/http-kernel/Kernel.php(185): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#10 /var/www/mautic/www_prod/app/AppKernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#11 /var/www/mautic/www_prod/app/middlewares/CORSMiddleware.php(92): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#12 /var/www/mautic/www_prod/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#13 /var/www/mautic/www_prod/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#14 /var/www/mautic/www_prod/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#15 /var/www/mautic/www_prod/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#16 /var/www/mautic/www_prod/index.php(34): Stack\\run(Object(Stack\\StackedHttpKernel))\n#17 {main}"}

**Comment by YannickBiet** [comment]
Seems our file contain an extra column (not named in header, last character is the delimeter) maybe the origin of the bug

As soon as i deleted it from both header and all CSV lines, it worked.

I am quite confident the bug is due to the missing column title ? (mautic should create a default name like Column Nb1

**Comment by Kedaranatha** [comment]
yes, same there. it was ok in previous versions. now i have to edit all CSV's (CSV format the same)

**Comment by andrekutianski** [comment]
Same problem here, but the contacts import don't come back :cry:

**Comment by YannickBiet** [comment]
@andrekutianski just log out and log in back, for me it was unlocking the import module screen for one more try (until I find the problem was in the source file that was handled a different way in 2.10.1)

**Comment by isleshocky77** [comment]
This issue duplicates #4937

**Comment by dbhurley** [comment]
Duplicate.
