### ISSUE TITLE
Import of google contacts from CSV fails with SQL exception 

### ISSUE THREAD

**Issue by galvani** [mautic/mautic#5476]
What type of report is this:
Bug report

## Description:
While importing CSV from exported google contacts; the import fails with:
```
An exception occurred while executing 'INSERT INTO imports (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, dir, file, original_file, line_count, inserted_count, updated_count, ignored_count, priority, status, date_started, date_ended, object, properties) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-12-21 12:04:25", 1, "Jan Kozak", null, null, null, null, null, null, null, "import.csv", null, 0, 0, 0, 0, 512, 1, null, null, "lead", "[]"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null
```

![image](https://user-images.githubusercontent.com/556426/34255274-3c777052-e650-11e7-8265-757b060c2b3d.png)

## If a bug:
Mautic version: a45596dcae7116098aaacc5a476f11cd7be1c1e1
PHP version: 5.6.32

### Steps to reproduce:
1. Try to import google csc

 
### Log errors: 
```
[2017-12-21 12:03:28] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /var/www/html/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /var/www/html/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(114): Mautic\\CoreBundle\\Doctrine\\Type\\ArrayType->convertToDatabaseValue(Array, Object(Doctrine\\DBAL\\Platforms\\MySQL57Platform))
#1 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(277): Doctrine\\DBAL\\Statement->bindValue(7, Array, 'array')
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->executeInserts()
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\\ORM\\UnitOfWork->executeInserts(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\\ORM\\UnitOfWork->commit(Object(Mautic\\CoreBundle\\Entity\\AuditLog))
#5 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(782): Doctrine\\ORM\\EntityManager->flush(Object(Mautic\\CoreBundle\\Entity\\AuditLog))
#6 /var/www/html/app/bundles/CoreBundle/Model/AuditLogModel.php(65): Mautic\\CoreBundle\\Entity\\CommonRepository->saveEntity(Object(Mautic\\CoreBundle\\Entity\\AuditLog))
#7 /var/www/html/app/bundles/LeadBundle/EventListener/ImportSubscriber.php(75): Mautic\\CoreBundle\\Model\\AuditLogModel->writeToLog(Array)
#8 [internal function]: Mautic\\LeadBundle\\EventListener\\ImportSubscriber->onImportPostSave(Object(Mautic\\LeadBundle\\Event\\ImportEvent), 'mautic.lead_imp...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#9 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Mautic\\LeadBundle\\Event\\ImportEvent), 'mautic.lead_imp...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#10 [internal function]: Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\LeadBundle\\Event\\ImportEvent), 'mautic.lead_imp...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#11 /var/www/html/app/cache/dev/classes.php(2253): call_user_func(Object(Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener), Object(Mautic\\LeadBundle\\Event\\ImportEvent), 'mautic.lead_imp...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#12 /var/www/html/app/cache/dev/classes.php(2168): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.lead_imp...', Object(Mautic\\LeadBundle\\Event\\ImportEvent))
#13 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(138): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('mautic.lead_imp...', Object(Mautic\\LeadBundle\\Event\\ImportEvent))
#14 /var/www/html/app/bundles/LeadBundle/Model/ImportModel.php(689): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('mautic.lead_imp...', Object(Mautic\\LeadBundle\\Event\\ImportEvent))
#15 /var/www/html/app/bundles/CoreBundle/Model/FormModel.php(115): Mautic\\LeadBundle\\Model\\ImportModel->dispatchEvent('post_save', Object(Mautic\\LeadBundle\\Entity\\Import), true, NULL)
#16 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(422): Mautic\\CoreBundle\\Model\\FormModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Import))
#17 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(475): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
#18 [internal function]: Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#19 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(142): call_user_func_array(Array, Array)
#20 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#21 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/app/AppKernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /var/www/html/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#28 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#29 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#30 /var/www/html/index_dev.php(28): Stack\
un(Object(Stack\\StackedHttpKernel))
#31 {main}
"} 
[2017-12-21 12:03:28] mautic.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 163) {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:163)
[stacktrace]
#0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(47): Symfony\\Component\\HttpFoundation\\JsonResponse->setData(Array)
#1 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(440): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500)
#2 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(223): Mautic\\CoreBundle\\Controller\\CommonController->ajaxAction(Array)
#3 /var/www/html/app/bundles/CoreBundle/Controller/ExceptionController.php(117): Mautic\\CoreBundle\\Controller\\CommonController->delegateView(Array)
#4 [internal function]: Mautic\\CoreBundle\\Controller\\ExceptionController->showAction(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\Debug\\Exception\\FlattenException), Object(Symfony\\Bridge\\Monolog\\Logger))
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(142): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#7 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2, false)
#8 /var/www/html/app/bundles/CoreBundle/EventListener/ExceptionListener.php(81): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2, false)
#9 [internal function]: Mautic\\CoreBundle\\EventListener\\ExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#10 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#11 [internal function]: Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#12 /var/www/html/app/cache/dev/classes.php(2253): call_user_func(Object(Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener), Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#13 /var/www/html/app/cache/dev/classes.php(2168): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#14 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(138): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#15 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(219): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#16 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(73): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Doctrine\\DBAL\\Types\\ConversionException), Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#17 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/AppKernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#26 /var/www/html/index_dev.php(28): Stack\
un(Object(Stack\\StackedHttpKernel))
#27 {main}
"} 
[2017-12-21 12:03:28] mautic.ERROR: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded - in file /var/www/html/vendor/symfony/http-foundation/JsonResponse.php - at line 163  
[2017-12-21 12:04:15] mautic.DEBUG: IMPORT(): import cannot be processed because SplFileObject cannot read the file  
[2017-12-21 12:04:15] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO imports (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, dir, file, original_file, line_count, inserted_count, updated_count, ignored_count, priority, status, date_started, date_ended, object, properties) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-12-21 12:04:15", 1, "Jan Kozak", null, null, null, null, null, null, null, "import.csv", null, 0, 0, 0, 0, 512, 4, "2017-12-21 12:04:15", null, "lead", "{\"status_info\":\"SplFileObject cannot read the file\"}"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO imports (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, dir, file, original_file, line_count, inserted_count, updated_count, ignored_count, priority, status, date_started, date_ended, object, properties) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2017-12-21 12:04:15\", 1, \"Jan Kozak\", null, null, null, null, null, null, null, \"import.csv\", null, 0, 0, 0, 0, 512, 4, \"2017-12-21 12:04:15\", null, \"lead\", \"{\\\"status_info\\\":\\\"SplFileObject cannot read the file\\\"}\"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(178): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO imp...', Array)
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\\DBAL\\Statement->execute()
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->executeInserts()
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\\ORM\\UnitOfWork->executeInserts(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\\ORM\\UnitOfWork->commit(Object(Mautic\\LeadBundle\\Entity\\Import))
#6 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(782): Doctrine\\ORM\\EntityManager->flush(Object(Mautic\\LeadBundle\\Entity\\Import))
#7 /var/www/html/app/bundles/CoreBundle/Model/FormModel.php(114): Mautic\\CoreBundle\\Entity\\CommonRepository->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Import))
#8 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(254): Mautic\\CoreBundle\\Model\\FormModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Import))
#9 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(475): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
#10 [internal function]: Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#11 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(142): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#13 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/AppKernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#22 /var/www/html/index_dev.php(28): Stack\
un(Object(Stack\\StackedHttpKernel))
#23 {main}
"} 
[2017-12-21 12:04:25] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO imports (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, dir, file, original_file, line_count, inserted_count, updated_count, ignored_count, priority, status, date_started, date_ended, object, properties) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2017-12-21 12:04:25", 1, "Jan Kozak", null, null, null, null, null, null, null, "import.csv", null, 0, 0, 0, 0, 512, 1, null, null, "lead", "[]"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO imports (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, dir, file, original_file, line_count, inserted_count, updated_count, ignored_count, priority, status, date_started, date_ended, object, properties) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, \"2017-12-21 12:04:25\", 1, \"Jan Kozak\", null, null, null, null, null, null, null, \"import.csv\", null, 0, 0, 0, 0, 512, 1, null, null, \"lead\", \"[]\"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dir' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(178): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO imp...', Array)
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\\DBAL\\Statement->execute()
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->executeInserts()
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\\ORM\\UnitOfWork->executeInserts(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\\ORM\\UnitOfWork->commit(Object(Mautic\\LeadBundle\\Entity\\Import))
#6 /var/www/html/app/bundles/CoreBundle/Entity/CommonRepository.php(782): Doctrine\\ORM\\EntityManager->flush(Object(Mautic\\LeadBundle\\Entity\\Import))
#7 /var/www/html/app/bundles/CoreBundle/Model/FormModel.php(114): Mautic\\CoreBundle\\Entity\\CommonRepository->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Import))
#8 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(138): Mautic\\CoreBundle\\Model\\FormModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Import))
#9 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(475): Mautic\\LeadBundle\\Controller\\ImportController->queueAction(0, '')
#10 [internal function]: Mautic\\CoreBundle\\Controller\\CommonController->executeAction('queue', 0, 0, '')
#11 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(142): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#13 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/AppKernel.php(132): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#22 /var/www/html/index_dev.php(28): Stack\
un(Object(Stack\\StackedHttpKernel))
#23 {main}
"} 
```

**Comment by Bizcrony** [comment]
are you importing very huge data ?

**Comment by galvani** [comment]
It's 900 items.

**Comment by Bizcrony** [comment]
why dont you try with CSV file import in contact tab?

**Comment by galvani** [comment]
That's what I did

**Comment by Bizcrony** [comment]
@galvani that means CSV has some issue in fact. Try with 20 row only.

**Comment by galvani** [comment]
The import is no longer possible. When I try to reach the import page, the exception is thrown.

**Comment by dbhurley** [comment]
It looks like a problem with the fields in your CSV instead of Mautic.
