### ISSUE TITLE
Database connection error #0 after upgrading 1.2.4 >> 2.12.1

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5542]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes

## Description:
Upgrading from 1.2.4 to 2.12.1 is very stressful.

## If a bug:

| Q   | A
| --- | ---
Mautic v | 2.12.1 (upgrading from 1.2.4)
PHP v | 5.6.33 (also tried 7.0.x)

### Steps to reproduce:
1. Attempted to upgrade from 1.2.4 from within mautic dashboard.  1.2.4 was working ok.  This failed (upgrade never finishes)
2. Found the [Uh Oh article](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful#5-try-to-update-files-manually) and attempted all the steps I could, including the final one of manually installing mautic.  
3. I copied the old /app/config/local.php file and attempted to load mautic and I keep getting 
` Database connection error (code #0)`

4. I do have local copy of database and old (1.2.4) mautic folder.

### Log errors: 

**Reverse chronological order; start from bottom**

``` Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] Database connection error (code #0) - in file /...../public_html/mautic/app/AppKernel.php - at line 119
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #9 /...../public_html/mautic/index.php(34): Stack\\run(Object(Stack\\StackedHttpKernel))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #8 /...../public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #7 /...../public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #6 /...../public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #5 /...../public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #4 /...../public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #3 /...../public_html/mautic/app/AppKernel.php(116): Doctrine\\DBAL\\Connection->connect()
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #2 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, '', '', Array)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #1 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\\DBAL\\DBALException::driverException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #0 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] Next exception 'Doctrine\\DBAL\\Exception\\ConnectionException' with message 'An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'venus.innerplanet.com' (using password: NO)' in /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #8 /...../public_html/mautic/index.php(34): Stack\\run(Object(Stack\\StackedHttpKernel))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #7 /...../public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #6 /...../public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #5 /...../public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #4 /...../public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #3 /...../public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #2 /...../public_html/mautic/app/AppKernel.php(116): Doctrine\\DBAL\\Connection->connect()
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #1 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, '', '', Array)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #0 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\\DBAL\\Driver\\PDOConnection::__construct('mysql:host=127....', '', '', Array)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] Next exception 'Doctrine\\DBAL\\Driver\\PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'venus.innerplanet.com' (using password: NO)' in /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #9 /...../public_html/mautic/index.php(34): Stack\\run(Object(Stack\\StackedHttpKernel))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #8 /...../public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #7 /...../public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #6 /...../public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #5 /...../public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #4 /...../public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #3 /...../public_html/mautic/app/AppKernel.php(116): Doctrine\\DBAL\\Connection->connect()
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #2 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, '', '', Array)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #1 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', '', '', Array)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] #0 /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', '', '', Array)
[Wed Jan 10 04:46:14 2018] [error] [client xxx.xxx.xxx.xxx] exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'venus.innerplanet.com' (using password: NO)' in /...../public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
```

---
Considering just a fresh install of mautic to bring it to 2.12.1  I was just REALLY upset at how many hours i put into this.  

Also, does this mean that it would be easier to just export contacts/campaigns and then just re-import them?  

Should there be an options like "import from older mautic installation/database"

**Comment by KonstantinCodes** [comment]
@4evermaat the logs say that "Access denied for user 'root'@'****' (using password: NO)".
Have you considered to set the PW?

**Comment by 4evermaat** [comment]
@KonstantinCodes 
I looked in the old local.php and i see` 'db_password' => 'xxxxxxxxxxx',`

is there another place to set/check the password?

**Comment by escopecz** [comment]
No, the db password is just there. But you have to clear the app/cache after you make any change to app/config/local.php. Did you clear the cache?

**Comment by escopecz** [comment]
And there is recommendation to use the update script for updates within every new release announcement.

https://www.mautic.org/topic/2-12-1-released/

Especially if you missed so many versions.

**Comment by 4evermaat** [comment]
@escopecz, I don't remember if I cleared the cache AFTER installing the new mautic / uploading the local file.
  In the old version, there was some option in the configuration tab to optimize database or clear

I used the update option within the mautic dashboard.   What is the difference?  ~~cant a user just run upgrade.php from the browser?~~ The most straightforward method I've seen.  Not sure why this is not in your documentation...or in the dashboard.

If there was like a maintenance.php within the mautic folder that I could run and then be presented with a master list of cleanup and fix tools where I just select from a radio or dropdown and it gets done.  Or put it in a tab in the dashboard (or both).  You have to assume not everyone will have a command line.

**Comment by 4evermaat** [comment]
Luckily there was no significant loss of contacts and such so "just starting fresh" was the least stressful option.  I use windows so I know that there are occassions where reinstalling a fresh OS image when there is a problem application (virtualized or real) is just easier than trying to deal with software tech support.  I would hate to have had an extensive database and lost it all because of an inability to connect with the old database.

**Comment by DensetsuNo** [comment]
I had this problem today. My AWS EC2 instance rebooted for some reason and from that moment onwards Mautic read `Database connection error (code #0)`.

As the way I solved the issue might help some other users is in the future write what happened in my specific case.

**Problem** _While rebooting my DB didn't reboot so it was "only" stopped, it sufficed restarting it and everything worked._

**How to solve it:**
- Log onto the instance via ssh (or whatever you use)
- Run `sudo service --status-all`
- As the problem was related to the DB check whether the DB (in my case mysql, has a minus `[ - ]` sign to its left. If that is the case it means that simply your db is not running and we have just to start it.
- run `sudo service mysql start`
- you are done

Back to mailing!

**Comment by aficiomaquinas** [comment]
I just had this problem today, my instance had been failing intermittently for the past month. Looking at the MySQL logs, it turns out the instance ran out of disk space. I resized the volume and the problem was fixed.
