### ISSUE TITLE
database connection error #0 ( mautic/app/AppKernel.php line 119)

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5721]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | No 
| Enhancement? |  No

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. not sure.  Just left mautic running as usual.  I have a cron job to update IP lookup every week.  And a cron job to clear cache every hour.
2. 
 
### Log errors: 

```
[18-Jan-2018 05:43:01 UTC] Doctrine\DBAL\Driver\Mysqli\MysqliException: Connection timed out in /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php:73
Stack trace:
#0 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(36): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->__construct(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#1 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#2 /rootuser/public_html/mautic/app/AppKernel.php(116): Doctrine\DBAL\Connection->connect()
#3 /rootuser/public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /rootuser/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /rootuser/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /rootuser/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /rootuser/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 /rootuser/public_html/mautic/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#9 {main}

Next Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: Connection timed out in /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
Stack trace:
#0 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#1 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(38): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\Mysqli\Driver), Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#2 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#3 /rootuser/public_html/mautic/app/AppKernel.php(116): Doctrine\DBAL\Connection->connect()
#4 /rootuser/public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /rootuser/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /rootuser/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /rootuser/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /rootuser/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 /rootuser/public_html/mautic/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#10 {main}
[18-Jan-2018 05:43:02 UTC] Database connection error (code #0) - in file /rootuser/public_html/mautic/app/AppKernel.php - at line 119
[30-Jan-2018 04:48:46 UTC] Doctrine\DBAL\Driver\Mysqli\MysqliException: Connection timed out in /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php:73
Stack trace:
#0 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(36): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->__construct(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#1 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#2 /rootuser/public_html/mautic/app/AppKernel.php(116): Doctrine\DBAL\Connection->connect()
#3 /rootuser/public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /rootuser/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /rootuser/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /rootuser/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /rootuser/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 /rootuser/public_html/mautic/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#9 {main}

Next Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: Connection timed out in /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
Stack trace:
#0 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#1 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(38): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\Mysqli\Driver), Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#2 /rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#3 /rootuser/public_html/mautic/app/AppKernel.php(116): Doctrine\DBAL\Connection->connect()
#4 /rootuser/public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /rootuser/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /rootuser/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /rootuser/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /rootuser/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 /rootuser/public_html/mautic/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#10 {main}
[30-Jan-2018 04:48:47 UTC] Database connection error (code #0) - in file /rootuser/public_html/mautic/app/AppKernel.php - at line 119
```

---
**[repeat daily (multiple times some days) from 01 Feb 2018 to 18 Feb 2018]

Last repeated entry:**

---

```
[17-Feb-2018 07:31:35 UTC] Doctrine\DBAL\Driver\Mysqli\MysqliException: Connection timed out in /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php:73
Stack trace:
#0 /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(36): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->__construct(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#1 /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#2 /home/rootuser/public_html/mautic/app/AppKernel.php(116): Doctrine\DBAL\Connection->connect()
#3 /home/rootuser/public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /home/rootuser/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /home/rootuser/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /home/rootuser/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/rootuser/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 /home/rootuser/public_html/mautic/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#9 {main}

Next Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: Connection timed out in /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
Stack trace:
#0 /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#1 /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php(38): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\Mysqli\Driver), Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#2 /home/rootuser/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\Mysqli\Driver->connect(Array, 'rootuser_maut20...', '0!9JMSp.S1', Array)
#3 /home/rootuser/public_html/mautic/app/AppKernel.php(116): Doctrine\DBAL\Connection->connect()
#4 /home/rootuser/public_html/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /home/rootuser/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /home/rootuser/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/rootuser/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/rootuser/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 /home/rootuser/public_html/mautic/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#10 {main}
[17-Feb-2018 07:31:35 UTC] Database connection error (code #0) - in file /home/rootuser/public_html/mautic/app/AppKernel.php - at line 119
```

At least with the old mautic 1.2.3, i installed it once and then forgot about it.

**Comment by 4evermaat** [comment]
After contacting webhost, I found out that the server was upgraded around the time the errors occurred. 
 The database was pointing to the old server.  They created links to repoint the database to the new location.

They said to make sure the database link posts to `localhost` and then it would automatically point to the latest location.    Not sure why mautic wouldn't just use this `localhost` link as default

**Comment by dbhurley** [comment]
It's a good question. I thought initially that Doctrine required the actual link instead of `localhost` but that may not be correct. We should explore whether there's benefit to using `localhost` instead.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
