### ISSUE TITLE
Uncaught Guzzle exceptions in Pipedrive can kill campaigns and other actions that save a Contact

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#6877]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Guzzle throws an exception for any non-200 responses which can any action that updates a contact which trigger's Pipedrive's exporter. 

For example, when executing a campaign that updates the points for a contact, the campaign script is halted due to 

```
"CAMPAIGN: Client error: `GET https://xxxxxxx.pipedrive.com/v1/persons/find?api_token=xxxxxxxx&term=bradtke.iliana%40mailinator.com&search_by_email=1` resulted in a `402 Payment Required` response:
{"success":false,"error":"Company account is not open (possible reason: trial expired, payment details not entered)","re (truncated...)
```

Here's a full trace
```

#0 vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) 
#1 vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) 
#2 vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) 
#3 vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() 
#4 vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true) 
#5 vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() 
#6 vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() 
#7 vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() 
#8 vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() 
#9 vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait() 
#10 plugins/MauticCrmBundle/Services/Transport.php(36): GuzzleHttp\Client->request('GET', 'https://mautic2...', Array) 
#11 plugins/MauticCrmBundle/Api/PipedriveApi.php(130): MauticPlugin\MauticCrmBundle\Services\Transport->get('https://mautic2...', Array) 
#12 plugins/MauticCrmBundle/Integration/Pipedrive/Export/LeadExport.php(52): MauticPlugin\MauticCrmBundle\Api\PipedriveApi->findByEmail('huel.carroll@ma...') 
#13 plugins/MauticCrmBundle/Integration/Pipedrive/Export/LeadExport.php(92): MauticPlugin\MauticCrmBundle\Integration\Pipedrive\Export\LeadExport->create(Object(Mautic\LeadBundle\Entity\Lead)) 
#14 plugins/MauticCrmBundle/EventListener/LeadSubscriber.php(84): MauticPlugin\MauticCrmBundle\Integration\Pipedrive\Export\LeadExport->update(Object(Mautic\LeadBundle\Entity\Lead)) 
#15 [internal function]: MauticPlugin\MauticCrmBundle\EventListener\LeadSubscriber->onLeadPostSave(Object(Mautic\LeadBundle\Event\LeadEvent), 'mautic.lead_pos...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#16 vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(Mautic\LeadBundle\Event\LeadEvent), 'mautic.lead_pos...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#17 vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'mautic.lead_pos...', Object(Mautic\LeadBundle\Event\LeadEvent)) 
#18 app/bundles/LeadBundle/Model/LeadModel.php(484): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('mautic.lead_pos...', Object(Mautic\LeadBundle\Event\LeadEvent)) 
#19 app/bundles/CoreBundle/Model/FormModel.php(115): Mautic\LeadBundle\Model\LeadModel->dispatchEvent('post_save', Object(Mautic\LeadBundle\Entity\Lead), false, Object(Mautic\LeadBundle\Event\LeadEvent)) 
#20 app/bundles/LeadBundle/Model/LeadModel.php(545): Mautic\CoreBundle\Model\FormModel->saveEntity(Object(Mautic\LeadBundle\Entity\Lead), true) 
#21 app/bundles/LeadBundle/EventListener/CampaignSubscriber.php(265): Mautic\LeadBundle\Model\LeadModel->saveEntity(Object(Mautic\LeadBundle\Entity\Lead)) 
#22 [internal function]: Mautic\LeadBundle\EventListener\CampaignSubscriber->onCampaignTriggerActionChangePoints(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.lead.on_...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#23 vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.lead.on_...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#24 vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'mautic.lead.on_...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent)) 
#25 app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('mautic.lead.on_...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent)) 
#26 app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(127): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchEventName('mautic.lead.on_...', Array, Object(Mautic\CampaignBundle\Entity\LeadEventLog)) 
#27 app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php(121): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchCustomEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection), NULL, Object(Mautic\CampaignBundle\Event\PendingEvent)) 
#28 app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php(73): Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection)) 
#29 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(228): Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection)) 
#30 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(195): Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter)) 
#31 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(274): Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter), false) 
#32 app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(238): Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter)) 
#33 app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(137): Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent() 
#34 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(389): Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute(Object(Mautic\CampaignBundle\Entity\Campaign), Object(Mautic\CampaignBundle\Executioner\ContactFinder\Limiter\ContactLimiter), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#35 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(346): Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff() 
#36 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(277): Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign(Object(Mautic\CampaignBundle\Entity\Campaign)) 
#37 vendor/symfony/console/Command/Command.php(242): Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#38 vendor/symfony/console/Application.php(861): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#39 vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#40 vendor/symfony/framework-bundle/Console/Application.php(84): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#41 vendor/symfony/console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#42 app/console(41): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#43 {main}
```

Pipedrive should be using try/catch around it's API calls to prevent this and log errors instead.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. Configure Pipedrive incorrectly to result in a non 200 response
2. Update a contact which should trigger Pipedrive's exporter
3. Note the uncaught exception
 
### Log errors

See above

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
@kuzmany are you the community's Pipedrive expert? :-)

**Comment by kuzmany** [comment]
I'll look on it.

**Comment by RCheesley** [comment]
@alanhartless @kuzmany has this been addressed? Presuming so but not seeing linked PR's!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
