### ISSUE TITLE
ORMInvalidArgumentException

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6957]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
My Mautic log is 

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.32-0ubuntu0.16.04.1
| Browser | Any

### Steps to reproduce
1. Add asset to Mautic.
2. Create `<a>` link to asset on website.
3. Download asset from incognito browser. [Possibly—exact reproduction sequence unknown.]
 
### Log errors

```
[04-Dec-2018 01:19:19 UTC] Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(852): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Mautic\LeadBundle\Entity\Lead))
#1 /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(740): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Mautic\LeadBundle\Entity\Lead))
#2 /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(452): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Mautic\AssetBundle\Entity\Download))
#3 /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(765): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#4 /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(340): Doctrine\ORM\UnitOfWork->computeChangeSets()
#5 /var/www/html/[servername]/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/html/[servername]/app/bundles/AssetBundle/Model/AssetModel.php(314): Doctrine\ORM\EntityManager->flush()
#7 /var/www/html/[servername]/app/bundles/AssetBundle/Controller/PublicController.php(77): Mautic\AssetBundle\Model\AssetModel->trackDownload(Object(Mautic\AssetBundle\Entity\Asset), Object(Symfony\Component\HttpFoundation\Request), 200)
#8 /var/www/html/[servername]/vendor/symfony/http-kernel/HttpKernel.php(135): Mautic\AssetBundle\Controller\PublicController->downloadAction('1:asset_id')
#9 /var/www/html/[servername]/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/html/[servername]/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/[servername]/vendor/symfony/http-kernel/Kernel.php(183): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/html/[servername]/app/AppKernel.php(133): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/html/[servername]/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/html/[servername]/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/html/[servername]/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/[servername]/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/html/[servername]/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 /var/www/html/[servername]/index.php(34): Stack\run(Object(Stack\StackedHttpKernel))
#19 {main}
```

**Comment by AkkuFresh** [comment]
The too same error message appears on the Mautic 2.15.0 with PHP 7.2

**Comment by AkkuFresh** [comment]
This issue still exist, with error messages:

```
[08-Jun-2019 11:48:00 UTC] Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(852): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Mautic\LeadBundle\Entity\Lead))
#1 /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(740): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Mautic\LeadBundle\Entity\Lead))
#2 /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(452): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Mautic\AssetBundle\Entity\Download))
#3 /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(765): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#4 /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(340): Doctrine\ORM\UnitOfWork->computeChangeSets()
#5 /home/[path-to-mautic]/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /home/[path-to-mautic]/app/bundles/AssetBundle/Model/AssetModel.php(314): Doctrine\ORM\EntityManager->flush()
#7 /home/[path-to-mautic]/app/bundles/AssetBundle/Controller/PublicController.php(86): Mautic\AssetBundle\Model\AssetModel->trackDownload(Object(Mautic\AssetBundle\Entity\Asset), Object(Symfony\Component\HttpFoundation\Request), 200)
#8 /home/[path-to-mautic]/vendor/symfony/http-kernel/HttpKernel.php(135): Mautic\AssetBundle\Controller\PublicController->downloadAction('10:szolgaltatas...')
#9 /home/[path-to-mautic]/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /home/[path-to-mautic]/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home/[path-to-mautic]/vendor/symfony/http-kernel/Kernel.php(183): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home/[path-to-mautic]/app/AppKernel.php(141): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home/[path-to-mautic]/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home/[path-to-mautic]/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home/[path-to-mautic]/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home/[path-to-mautic]/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home/[path-to-mautic]/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 /home/[path-to-mautic]/index.php(37): Stack\run(Object(Stack\StackedHttpKernel))
#19 {main}
```

**Comment by AkkuFresh** [comment]
The issue still exist with Mautic v.2.16.1 and PHP 7.3.16

In this Mautic instance all downloads related to the links sent by email and sometimes these emails are forwarded, and the asset can be downloaded by user unknown for the system.

```
[31-Mar-2020 16:39:05 UTC] Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(852): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Mautic\LeadBundle\Entity\Lead))
#1 <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(740): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Mautic\LeadBundle\Entity\Lead))
#2 <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(452): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Mautic\AssetBundle\Entity\Download))
#3 <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(765): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#4 <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(340): Doctrine\ORM\UnitOfWork->computeChangeSets()
#5 <path-to-mautic-root>/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 <path-to-mautic-root>/app/bundles/AssetBundle/Model/AssetModel.php(314): Doctrine\ORM\EntityManager->flush()
#7 <path-to-mautic-root>/app/bundles/AssetBundle/Controller/PublicController.php(86): Mautic\AssetBundle\Model\AssetModel->trackDownload(Object(Mautic\AssetBundle\Entity\Asset), Object(Symfony\Component\HttpFoundation\Request), 200)
#8 <path-to-mautic-root>/vendor/symfony/http-kernel/HttpKernel.php(135): Mautic\AssetBundle\Controller\PublicController->downloadAction('32:asset-name...')
#9 <path-to-mautic-root>/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 <path-to-mautic-root>/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 <path-to-mautic-root>/vendor/symfony/http-kernel/Kernel.php(183): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 <path-to-mautic-root>/app/AppKernel.php(141): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 <path-to-mautic-root>/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 <path-to-mautic-root>/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 <path-to-mautic-root>/app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 <path-to-mautic-root>/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 <path-to-mautic-root>/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 <path-to-mautic-root>/index.php(37): Stack\run(Object(Stack\StackedHttpKernel))
#19 {main}
```

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by trianity** [comment]
@npracht I am sorry for the delay. 
The issue is still exist on the latest Mautic v3.1.2 
PHP Version 7.3.23

```
[03-Nov-2020 11:29:54 UTC] Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:102
Stack trace:
#0 /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3460): Doctrine\ORM\ORMInvalidArgumentException::newEntitiesFoundThroughRelationships(Array)
#1 /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(365): Doctrine\ORM\UnitOfWork->assertThatThereAreNoUnintentionallyNonPersistedAssociations()
#2 /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(368): Doctrine\ORM\UnitOfWork->commit(NULL)
#3 /path-to-mautic/app/bundles/AssetBundle/Model/AssetModel.php(312): Doctrine\ORM\EntityManager->flush()
#4 /path-to-mautic/app/bundles/AssetBundle/Controller/PublicController.php(73): Mautic\AssetBundle\Model\AssetModel->trackDownload(Object(Mautic\AssetBundle\Entity\Asset), Object(Symfony\Component\HttpFoundation\Request), 200)
#5 /path-to-mautic/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\AssetBundle\Controller\PublicController->downloadAction('18:kasza-tamas-...')
#6 /path-to-mautic/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /path-to-mautic/vendor/symfony/http-kernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /path-to-mautic/app/AppKernel.php(104): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /path-to-mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /path-to-mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /path-to-mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /path-to-mautic/app/middlewares/TrustMiddleware.php(51): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /path-to-mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /path-to-mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#15 /path-to-mautic/index.php(24): Stack\run(Object(Stack\StackedHttpKernel))
#16 {main}
```

**Comment by tomekkowalczyk** [comment]
I have the same problem Mautic 3.2.4  PHP 7.3.12

you know exactly what causes it?

`[Wed [1;33m[KJan 13 15:29:30.711116 2021[m[K] [php7:notice] [pid 19621] [client 147.92.179.114:30926] Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\\AssetBundle\\Entity\\Download#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in /home/www/www/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:102\nStack trace:\n#0 /home/www/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3460): Doctrine\\ORM\\ORMInvalidArgumentException::newEntitiesFoundThroughRelationships(Array)\n#1 /home/www/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(365): Doctrine\\ORM\\UnitOfWork->assertThatThereAreNoUnintentionallyNonPersistedAssociations()\n#2 /home/www/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(368): Doctrine\\ORM\\UnitOfWork->commit(NULL)\n#3 /home/www/www/app/bundles/AssetBundle/Model/AssetModel.php(285): Doctrine\\ORM\\EntityManager->flush()\n#4 /home/www/www/app/bundles/AssetBundle/Controller/PublicController.php(73): Mautic\\AssetBundle\\Model\\AssetModel->trackDownload(Object(Mautic\\AssetBundle\\Entity\\Asset), Object(Symfony\\Component\\HttpFoundation\\Request), 200)\n#5 /home/www/www/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\AssetBundle\\Controller\\PublicController->downloadAction('105:webexmeetin...')\n#6 /home/www/www/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#7 /home/www/www/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 /home/www/www/app/AppKernel.php(98): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 /home/www/www/app/middlewares/CORSMiddleware.php(76): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#10 /home/www/www/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#11 /home/www/www/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#12 /home/www/www/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#13 /home/www/www/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#14 /home/www/www/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#15 /home/www/www/index.php(24): Stack\\run(Object(Stack\\StackedHttpKernel))\n#16 {main}`

**Comment by tomekkowalczyk** [comment]
@RCheesley request to open a task, problem still exists in version 3.3.3

**Comment by RCheesley** [comment]
@tomekkowalczyk would you be up for digging into what is causing this and maybe making a PR if there isn't one already? I couldn't see one being linked up to the issue so assuming it hasn't been resolved yet.

**Comment by trianity** [comment]
Dear @RCheesley the issue still exists on Mautic v.4.4.0 (composer based) with PHP 8.0.19.
The fresh log output:
```
[16-Jul-2022 15:43:00 UTC] Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:100
Stack trace:
#0 /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3522): Doctrine\ORM\ORMInvalidArgumentException::newEntitiesFoundThroughRelationships()
#1 /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(391): Doctrine\ORM\UnitOfWork->assertThatThereAreNoUnintentionallyNonPersistedAssociations()
#2 /path-to-mautic/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(398): Doctrine\ORM\UnitOfWork->commit()
#3 /path-to-mautic/docroot/app/bundles/AssetBundle/Model/AssetModel.php(301): Doctrine\ORM\EntityManager->flush()
#4 /path-to-mautic/docroot/app/bundles/AssetBundle/Controller/PublicController.php(64): Mautic\AssetBundle\Model\AssetModel->trackDownload()
#5 /path-to-mautic/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\AssetBundle\Controller\PublicController->downloadAction()
#6 /path-to-mautic/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#7 /path-to-mautic/vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle()
#8 /path-to-mautic/docroot/app/AppKernel.php(115): Symfony\Component\HttpKernel\Kernel->handle()
#9 /path-to-mautic/docroot/app/middlewares/CORSMiddleware.php(82): AppKernel->handle()
#10 /path-to-mautic/docroot/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\Middleware\CORSMiddleware->handle()
#11 /path-to-mautic/docroot/app/middlewares/VersionCheckMiddleware.php(58): Mautic\Middleware\CatchExceptionMiddleware->handle()
#12 /path-to-mautic/docroot/app/middlewares/TrustMiddleware.php(42): Mautic\Middleware\VersionCheckMiddleware->handle()
#13 /path-to-mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle()
#14 /path-to-mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle()
#15 /path-to-mautic/docroot/index.php(24): Stack\run()
#16 {main}
```

**Comment by trianity** [comment]
Reopen with: #11340
