### ISSUE TITLE
Cannot access development environment

### ISSUE THREAD

**Issue by Looooong** [mautic/mautic#7393]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.15
| Browser | 

### Steps to reproduce
1. Fresh install from Github, switch to branch `master` (currently on commit `8abdcc73ce091f6a1deced817a9a4a7a2999967c`).
2. Go to `/index_dev.php`.
3. Receive 404 Not Found.
 
### Log errors
```log
[2019-04-08 10:21:51] event.INFO: An exception was thrown while getting the uncalled listeners. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): PHP Notice - Undefined index: frequency_number at /home/long/workspace/mautic/app/bundles/SmsBundle/Helper/SmsHelper.php:72)
[stacktrace]
#0 /home/long/workspace/mautic/app/bundles/SmsBundle/Helper/SmsHelper.php(72): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Un...', '/home/long/work...', 72, Array)
#1 /home/long/workspace/mautic/app/cache/dev/appDevDebugProjectContainer.php(11487): Mautic\\SmsBundle\\Helper\\SmsHelper->__construct(Object(Doctrine\\ORM\\EntityManager), Object(Mautic\\LeadBundle\\Model\\LeadModel), Object(Mautic\\CoreBundle\\Helper\\PhoneNumberHelper), Object(Mautic\\SmsBundle\\Model\\SmsModel), Object(Mautic\\PluginBundle\\Helper\\IntegrationHelper))
#2 /home/long/workspace/mautic/vendor/symfony/dependency-injection/Container.php(297): appDevDebugProjectContainer->getMautic_Helper_SmsService()
#3 /home/long/workspace/mautic/app/cache/dev/appDevDebugProjectContainer.php(15958): Symfony\\Component\\DependencyInjection\\Container->get('mautic.helper.s...')
#4 /home/long/workspace/mautic/vendor/symfony/dependency-injection/Container.php(297): appDevDebugProjectContainer->getMautic_Sms_Smsbundle_SubscriberService()
#5 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(169): Symfony\\Component\\DependencyInjection\\Container->get('mautic.sms.smsb...')
#6 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(111): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->lazyLoad('mautic.sms_post...')
#7 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(92): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->getListeners(NULL)
#8 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(167): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->getListeners()
#9 /home/long/workspace/mautic/vendor/symfony/http-kernel/DataCollector/EventDataCollector.php(48): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->getNotCalledListeners()
#10 /home/long/workspace/mautic/vendor/symfony/http-kernel/Profiler/Profiler.php(100): Symfony\\Component\\HttpKernel\\DataCollector\\EventDataCollector->lateCollect()
#11 /home/long/workspace/mautic/vendor/symfony/http-kernel/EventListener/ProfilerListener.php(152): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->saveProfile(Object(Symfony\\Component\\HttpKernel\\Profiler\\Profile))
#12 [internal function]: Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener->onKernelTerminate(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#13 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#14 [internal function]: Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#15 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Object(Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener), Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#16 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))
#17 /home/long/workspace/mautic/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(133): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))
#18 /home/long/workspace/mautic/vendor/symfony/http-kernel/HttpKernel.php(77): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))
#19 /home/long/workspace/mautic/vendor/symfony/http-kernel/Kernel.php(151): Symfony\\Component\\HttpKernel\\HttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\RedirectResponse))
#20 /home/long/workspace/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\Kernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\RedirectResponse))
#21 /home/long/workspace/mautic/vendor/stack/run/src/Stack/run.php(16): Stack\\StackedHttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\RedirectResponse))
#22 /home/long/workspace/mautic/index_dev.php(33): Stack\
un(Object(Stack\\StackedHttpKernel))
#23 {main}
"} 
[2019-04-08 10:21:51] event.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate".  
[2019-04-08 10:21:51] event.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelTerminate".  
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
I cannot reproduce. How did you install Mautic? What is the full URL with index_dev.php?

**Comment by Looooong** [comment]
I setup web server on my local machine using `nginx` and `php-fpm`. I couldn't access the development site because of an exception not being handled.

I switched to the built-in PHP web server (using `php -S`) and can access the development environment normally.

Still, you should look at `app/bundles/SmsBundle/Helper/SmsHelper.php(72)` where the exception is raised.

**Comment by escopecz** [comment]
I'm using 
```
$ php -v
PHP 7.2.12 (cli) (built: Nov  9 2018 11:00:45) ( NTS )
```
and I can't replicate it. If anyone could come up with detailed steps to replicate (what exactly triggers it) I will reopen this issue.
