### ISSUE TITLE
Default config values are not filled properly after clean installation.

### ISSUE THREAD

**Issue by hluchas** [mautic/mautic#8423]
## Bug Description
Default config values are not filled properly after clean installation.

| Q   | A
| --- | ---
| Mautic version | 3.x
| PHP version | 7.2
| Browser | Latest Chrome

### Steps to reproduce
1. Remove `app/config/local.php`
2. Install Mautic
3. Try to access app configuration form `/s/config/edit`
 
### Log errors
```
[2020-02-11 09:37:07] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "[email_frequency_number]": Expected a numeric." at /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php line 1087 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"[email_frequency_number]\": Expected a numeric. at /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php:1087, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Expected a numeric. at /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Extension/Core/DataTransformer/NumberToLocalizedStringTransformer.php:118)
[stacktrace]
#0 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php(348): Symfony\\Component\\Form\\Form->normToView('')
#1 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php(49): Symfony\\Component\\Form\\Form->setData('')
#2 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php(372): Symfony\\Component\\Form\\Extension\\Core\\DataMapper\\PropertyPathMapper->mapDataToForms(Array, Object(RecursiveIteratorIterator))
#3 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php(425): Symfony\\Component\\Form\\Form->setData(Array)
#4 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Extension/DataCollector/FormDataExtractor.php(71): Symfony\\Component\\Form\\Form->getNormData()
#5 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Extension/DataCollector/FormDataCollector.php(137): Symfony\\Component\\Form\\Extension\\DataCollector\\FormDataExtractor->extractDefaultData(Object(Symfony\\Component\\Form\\Form))
#6 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Extension/DataCollector/FormDataCollector.php(141): Symfony\\Component\\Form\\Extension\\DataCollector\\FormDataCollector->collectDefaultData(Object(Symfony\\Component\\Form\\Form))
#7 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Extension/DataCollector/EventListener/DataCollectorListener.php(57): Symfony\\Component\\Form\\Extension\\DataCollector\\FormDataCollector->collectDefaultData(Object(Symfony\\Component\\Form\\Form))
#8 /Users/lukas.drahy/dev/community-fork/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\Form\\Extension\\DataCollector\\EventListener\\DataCollectorListener->postSetData(Object(Symfony\\Component\\Form\\FormEvent), 'form.post_set_d...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#9 /Users/lukas.drahy/dev/community-fork/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'form.post_set_d...', Object(Symfony\\Component\\Form\\FormEvent))
#10 /Users/lukas.drahy/dev/community-fork/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(33): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('form.post_set_d...', Object(Symfony\\Component\\Form\\FormEvent))
#11 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php(377): Symfony\\Component\\EventDispatcher\\ImmutableEventDispatcher->dispatch('form.post_set_d...', Object(Symfony\\Component\\Form\\FormEvent))
#12 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/Form.php(476): Symfony\\Component\\Form\\Form->setData(Array)
#13 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/FormBuilder.php(210): Symfony\\Component\\Form\\Form->initialize()
#14 /Users/lukas.drahy/dev/community-fork/vendor/symfony/form/FormFactory.php(30): Symfony\\Component\\Form\\FormBuilder->getForm()
#15 /Users/lukas.drahy/dev/community-fork/app/bundles/ConfigBundle/Controller/ConfigController.php(56): Symfony\\Component\\Form\\FormFactory->create('Mautic\\\\ConfigBu...', Array, Array)
#16 /Users/lukas.drahy/dev/community-fork/app/bundles/CoreBundle/Controller/CommonController.php(449): Mautic\\ConfigBundle\\Controller\\ConfigController->editAction(0, '')
#17 /Users/lukas.drahy/dev/community-fork/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', 0, 0, '')
#18 /Users/lukas.drahy/dev/community-fork/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#19 /Users/lukas.drahy/dev/community-fork/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /Users/lukas.drahy/dev/community-fork/app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /Users/lukas.drahy/dev/community-fork/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /Users/lukas.drahy/dev/community-fork/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /Users/lukas.drahy/dev/community-fork/app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /Users/lukas.drahy/dev/community-fork/app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /Users/lukas.drahy/dev/community-fork/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 /Users/lukas.drahy/dev/community-fork/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /Users/lukas.drahy/dev/community-fork/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#28 /Users/lukas.drahy/dev/community-fork/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#29 {main}
"} 
```

It seems that there is applied to string conversion when default parameters are build.
Default parameters:
![Snímek obrazovky 2020-02-11 v 11 39 25](https://user-images.githubusercontent.com/12815758/74229770-506ee500-4cc3-11ea-8df9-5e95c5a6957c.png)

Dumped result used in form:
![Snímek obrazovky 2020-02-11 v 11 38 26](https://user-images.githubusercontent.com/12815758/74229806-667ca580-4cc3-11ea-9e5b-3a69e02eb75a.png)

**Comment by alanhartless** [comment]
@hluchas I fixed this in https://github.com/mautic/mautic/pull/8422
