### ISSUE TITLE
Changing campaigns on a contact details page results in 500

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8497]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Toggling the campaign membership through a contact's detail page results in 500s

| Q   | A
| --- | ---
| Mautic version | 3 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Go to a contacts details page and click the dropdown for more actions then "Campaigns"
2. Toggle campaigns (add or remove) for the contact and note that nothing happens. A 500 error is recorded. 
 
### Log errors
```
[2020-03-02 02:07:26] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "addLead" of class "Mautic\CampaignBundle\Model\CampaignModel"." at app/bundles/LeadBundle/Controller/AjaxController.php line 386 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"addLead\" of class \"Mautic\\CampaignBundle\\Model\\CampaignModel\". at app/bundles/LeadBundle/Controller/AjaxController.php:386)
[stacktrace]
#0 app/bundles/CoreBundle/Controller/AjaxController.php(131): Mautic\\LeadBundle\\Controller\\AjaxController->toggleLeadCampaignAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#1 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('toggleLeadCampa...', Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#2 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#3 vendor/symfony/framework-bundle/Controller/ControllerTrait.php(108): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#4 app/bundles/CoreBundle/Controller/AjaxController.php(109): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticLeadBundl...', Array)
#5 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#6 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#7 vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#16 index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#17 {main}
```
```
[2020-03-02 02:12:10] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "removeLead" of class "Mautic\CampaignBundle\Model\CampaignModel"." at app/bundles/LeadBundle/Controller/AjaxController.php line 386 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"removeLead\" of class \"Mautic\\CampaignBundle\\Model\\CampaignModel\". at app/bundles/LeadBundle/Controller/AjaxController.php:386)
[stacktrace]
#0 app/bundles/CoreBundle/Controller/AjaxController.php(131): Mautic\\LeadBundle\\Controller\\AjaxController->toggleLeadCampaignAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#1 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('toggleLeadCampa...', Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#2 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#3 vendor/symfony/framework-bundle/Controller/ControllerTrait.php(108): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#4 app/bundles/CoreBundle/Controller/AjaxController.php(109): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticLeadBundl...', Array)
#5 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#6 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#7 vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#16 index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#17 {main}
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Contact > Change individual contact campaigns from contact profile](https://trello.com/c/KLrw4DJb/42-contact-change-individual-contact-campaigns-from-contact-profile)

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/8526

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Contact > switch campaign assignemnt](https://trello.com/c/3yoMXTtH/299-contact-switch-campaign-assignemnt)
