### ISSUE TITLE
Exception when editing a DWC translation

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8512]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Editing the translation of a dynamic web content item causes an exception and prevents editing. 

| Q   | A
| --- | ---
| Mautic version | 2.16; 3.0
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a dynamic web content item
2. Create a second and configure it as the translation of the first
3. Edit the translation and note the error

### Log errors
```
[2020-03-04 02:25:39] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "PHP Notice - Object of class Closure could not be converted to int" at app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php line 142 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): PHP Notice - Object of class Closure could not be converted to int at app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php:142)
[stacktrace]
#0 app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php(142): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Ob...', '/Users/alan/Web...', 142, Array)
#1 [internal function]: Mautic\\CoreBundle\\Form\\ChoiceLoader\\EntityLookupChoiceLoader->Mautic\\CoreBundle\\Form\\ChoiceLoader\\{closure}(Object(Closure))
#2 app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php(144): array_map(Object(Closure), Array)
#3 app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php(83): Mautic\\CoreBundle\\Form\\ChoiceLoader\\EntityLookupChoiceLoader->getChoices(Array, true)
#4 vendor/symfony/form/ChoiceList/LazyChoiceList.php(87): Mautic\\CoreBundle\\Form\\ChoiceLoader\\EntityLookupChoiceLoader->loadChoiceList(NULL)
#5 vendor/symfony/form/ChoiceList/Factory/DefaultChoiceListFactory.php(52): Symfony\\Component\\Form\\ChoiceList\\LazyChoiceList->getChoices()
#6 vendor/symfony/form/ChoiceList/Factory/PropertyAccessDecorator.php(207): Symfony\\Component\\Form\\ChoiceList\\Factory\\DefaultChoiceListFactory->createView(Object(Symfony\\Component\\Form\\ChoiceList\\LazyChoiceList), Array, NULL, NULL, NULL, NULL)
#7 vendor/symfony/form/ChoiceList/Factory/CachingFactoryDecorator.php(131): Symfony\\Component\\Form\\ChoiceList\\Factory\\PropertyAccessDecorator->createView(Object(Symfony\\Component\\Form\\ChoiceList\\LazyChoiceList), Array, NULL, NULL, NULL, NULL)
#8 vendor/symfony/form/Extension/Core/Type/ChoiceType.php(428): Symfony\\Component\\Form\\ChoiceList\\Factory\\CachingFactoryDecorator->createView(Object(Symfony\\Component\\Form\\ChoiceList\\LazyChoiceList), Array, NULL, NULL, NULL, NULL)
#9 vendor/symfony/form/Extension/Core/Type/ChoiceType.php(185): Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType->createChoiceListView(Object(Symfony\\Component\\Form\\ChoiceList\\LazyChoiceList), Array)
#10 vendor/symfony/form/ResolvedFormType.php(148): Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType->buildView(Object(Symfony\\Component\\Form\\FormView), Object(Symfony\\Component\\Form\\Form), Array)
#11 vendor/symfony/form/ResolvedFormType.php(145): Symfony\\Component\\Form\\ResolvedFormType->buildView(Object(Symfony\\Component\\Form\\FormView), Object(Symfony\\Component\\Form\\Form), Array)
#12 vendor/symfony/form/ResolvedFormType.php(145): Symfony\\Component\\Form\\ResolvedFormType->buildView(Object(Symfony\\Component\\Form\\FormView), Object(Symfony\\Component\\Form\\Form), Array)
#13 vendor/symfony/form/Form.php(1005): Symfony\\Component\\Form\\ResolvedFormType->buildView(Object(Symfony\\Component\\Form\\FormView), Object(Symfony\\Component\\Form\\Form), Array)
#14 vendor/symfony/form/Form.php(1008): Symfony\\Component\\Form\\Form->createView(Object(Symfony\\Component\\Form\\FormView))
#15 app/bundles/CoreBundle/Controller/FormThemeTrait.php(29): Symfony\\Component\\Form\\Form->createView()
#16 app/bundles/DynamicContentBundle/Controller/DynamicContentController.php(328): Mautic\\CoreBundle\\Controller\\AbstractFormController->setFormTheme(Object(Symfony\\Component\\Form\\Form), 'MauticDynamicCo...', 'MauticDynamicCo...')
#17 app/bundles/CoreBundle/Controller/CommonController.php(449): Mautic\\DynamicContentBundle\\Controller\\DynamicContentController->editAction('2', '')
#18 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', '2', 0, '')
#19 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#20 vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#28 vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#29 index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#30 {main}
"} 
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dynamic Content > Edit existing DC](https://trello.com/c/v059dLCZ/293-dynamic-content-edit-existing-dc)

**Comment by RCheesley** [comment]
@alanhartless wondering if this remains in 3.2.1 as it was reported back during the 3.x UAT phase!

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.
