### ISSUE TITLE
Campaign "change contact stage" event does not work due to use of a non-existing method

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8521]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This bug has apparently been around for a very long time according to a code trace. But when trying to change the stage through a campaign action, an exception is thrown due to the use of a `$event->getName()` where `getName()` is not defined. 

| Q   | A
| --- | ---
| Mautic version | 2.16/3.0
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a stage
2. Create a campaign with an action to "change contact stage"
3. Execute the campaign
4. Note the error
 
### Log errors
```
[2020-03-05 00:48:17] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Mautic\CampaignBundle\Event\CampaignExecutionEvent::getName() (uncaught exception) at app/bundles/StageBundle/EventListener/CampaignSubscriber.php line 90 while running console command `mautic:campaigns:trigger`
[stack trace]
#0 vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\StageBundle\EventListener\CampaignSubscriber->onCampaignTriggerActionChangeStage(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.stage.on...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#1 vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.stage.on...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#2 vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'mautic.stage.on...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#3 vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('mautic.stage.on...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#4 app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(225): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('mautic.stage.on...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#5 app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(119): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchEventName('mautic.stage.on...', Array, Object(Mautic\CampaignBundle\Entity\LeadEventLog))
#6 app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php(110): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchCustomEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection), NULL, Object(Mautic\CampaignBundle\Event\PendingEvent))
#7 app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php(67): Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection))
#8 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(201): Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection))
#9 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(172): Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter))
#10 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(245): Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter), false)
#11 app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(222): Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter))
#12 app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(122): Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent()
#13 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(372): Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute(Object(Mautic\CampaignBundle\Entity\Campaign), Object(Mautic\CampaignBundle\Executioner\ContactFinder\Limiter\ContactLimiter), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(328): Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff()
#15 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(277): Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign(Object(Mautic\CampaignBundle\Entity\Campaign))
#16 vendor/symfony/console/Command/Command.php(255): Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(1001): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/framework-bundle/Console/Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 vendor/symfony/console/Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 bin/console(41): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stages -> Ensure contact can not move back to a stage that is has a lower weight than the stage it is currently in](https://trello.com/c/Ep9C8nCx/324-stages-ensure-contact-can-not-move-back-to-a-stage-that-is-has-a-lower-weight-than-the-stage-it-is-currently-in)

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stages -> Ensure contact changes stages through the Change Contact's Stage campaign action with a specific stage selected](https://trello.com/c/NXLY27pS/323-stages-ensure-contact-changes-stages-through-the-change-contacts-stage-campaign-action-with-a-specific-stage-selected)

**Comment by alanhartless** [comment]
This is actually fixed in #7812

**Comment by npracht** [comment]
Please test #8659

**Comment by mohit-rocks** [comment]
Please test https://github.com/mautic/mautic/pull/8969

**Comment by dennisameling** [comment]
This was fixed in https://github.com/mautic/mautic/pull/8907 which was in the 3.0.2 release - closing this issue
