### ISSUE TITLE
Deleting a theme causes a PHP warning ` Internal Server Error - PHP Warning - array_key_exists() expects parameter 2 to be array, null given`

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8523]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This doesn't seem to cause any major issues but was newly introduced in M3. When deleting a theme, a PHP warning is caused by data may not be an array. 

https://github.com/mautic/mautic/blob/0d5888471364e3d20a145089fba64f4fa515073f/app/bundles/CoreBundle/Controller/AbstractFormController.php#L142

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Go to themes
2. Upload a new theme
3. Delete the theme
 
### Log errors
```
[2020-03-05 02:04:21] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "PHP Warning - array_key_exists() expects parameter 2 to be array, null given" at app/bundles/CoreBundle/Controller/AbstractFormController.php line 142 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): PHP Warning - array_key_exists() expects parameter 2 to be array, null given at app/bundles/CoreBundle/Controller/AbstractFormController.php:142)
[stacktrace]
#0 [internal function]: Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(2, 'PHP Warning - a...', '/Users/alan/Web...', 142, Array)
#1 app/bundles/CoreBundle/Controller/AbstractFormController.php(142): array_key_exists('buttons', NULL)
#2 app/bundles/CoreBundle/Controller/ThemeController.php(48): Mautic\\CoreBundle\\Controller\\AbstractFormController->isFormCancelled(Object(Symfony\\Component\\Form\\Form))
#3 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\ThemeController->indexAction()
#4 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#5 vendor/symfony/framework-bundle/Controller/ControllerTrait.php(108): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#6 app/bundles/CoreBundle/Controller/CommonController.php(361): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticCoreBundl...', Array, Array)
#7 app/bundles/CoreBundle/Controller/CommonController.php(291): Mautic\\CoreBundle\\Controller\\CommonController->ajaxAction(Array)
#8 app/bundles/CoreBundle/Controller/ThemeController.php(197): Mautic\\CoreBundle\\Controller\\CommonController->postActionRedirect(Array)
#9 app/bundles/CoreBundle/Controller/CommonController.php(449): Mautic\\CoreBundle\\Controller\\ThemeController->deleteAction('archive', '')
#10 vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('delete', 'archive', 0, '')
#11 vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#12 vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 app/AppKernel.php(135): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#21 index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#22 {main}
"} 
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Themes -> Test custom themes can be deleted and that default themes cannot](https://trello.com/c/7GFadePU/340-themes-test-custom-themes-can-be-deleted-and-that-default-themes-cannot)

**Comment by alanhartless** [comment]
This is a duplicate of https://github.com/mautic/mautic/issues/8486
