### ISSUE TITLE
Site offline after latest update to 3.1.1

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#9264]
## Bug Description
This is what I see now after trying to update to Mautic 3.1.1

The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.

| Q   | A
| --- | ---
| Mautic version | 
3.1.1

| PHP version | 
7.3

| Browser | 
Any

### Steps to reproduce
1. Update Mautic from the UI
2. Wait and get the error.
 
### Log errors
No error logged on the server.

Mautic's log

wfuf7j8n8ebt@a2plcpnl0582 [~/public_html/accuware/mautic]$ cat error_log
[21-Aug-2020 14:08:44 UTC] UnexpectedValueException: internal corruption of phar "/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/unpack/temp.tar.gz" (__HALT_COMPILER(); not found) in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php:111
Stack trace:
#0 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php(111): PharData->__construct('/home/wfuf7j8n8...')
#1 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/CoreBundle/Controller/AjaxController.php(693): Mautic\CoreBundle\IpLookup\AbstractLocalDataLookup->downloadRemoteDataStore()
#2 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/CoreBundle/Controller/AjaxController.php(134): Mautic\CoreBundle\Controller\AjaxController->downloadIpLookupDataStoreAction(Object(Symfony\Component\HttpFoundation\Request), NULL)
#3 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/CoreBundle/Controller/AjaxController.php(119): Mautic\CoreBundle\Controller\AjaxController->executeAjaxAction('downloadIpLooku...', Object(Symfony\Component\HttpFoundation\Request), NULL)
#4 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\CoreBundle\Controller\AjaxController->delegateAjaxAction()
#5 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/symfony/http-kernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/AppKernel.php(104): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/TrustMiddleware.php(51): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request),1, true)
#13 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 /home/wfuf7j8n8ebt/public_html/accuware/mautic/index.php(24): Stack\run(Object(Stack\StackedHttpKernel))
#15 {main}
[25-Aug-2020 15:47:11 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 15:47:11 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 15:47:11 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:04:41 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:26:06 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:33:41 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:33:43 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:33:56 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:34:05 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:35:33 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:35:33 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[25-Aug-2020 16:35:33 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[08-Sep-2020 21:22:08 UTC] PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) in /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
Stack trace:
#0 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=loca...', 'mautic', 'Dpu!dXPOh43)', Array)
#1 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'mautic','Dpu!dXPOh43)', Array)
#2 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'mautic', 'Dpu!dXPOh43)', Array)
#3 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/AppKernel.php(97): Doctrine\DBAL\Connection->connect()
#4 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/TrustMiddleware.php(51): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#10 /home/wfuf7j8n8ebt/public_html/accuware/mautic/index.php(24): Stack\run(Object(Stack\StackedHttpKernel))
#11 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) in /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
Stack trace:
#0 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'mautic','Dpu!dXPOh43)', Array)
#1 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'mautic', 'Dpu!dXPOh43)', Array)
#2 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/AppKernel.php(97): Doctrine\DBAL\Connection->connect()
#3 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/TrustMiddleware.php(51): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 /home/wfuf7j8n8ebt/public_html/accuware/mautic/index.php(24): Stack\run(Object(Stack\StackedHttpKernel))
#10 {main}

Next Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) in /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93
Stack trace:
#0 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(154): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(28): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException))
#3 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'mautic', 'Dpu!dXPOh43)', Array)
#4 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/AppKernel.php(97): Doctrine\DBAL\Connection->connect()
#5 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/middlewares/TrustMiddleware.php(51): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home/wfuf7j8n8ebt/public_html/accuware/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 /home/wfuf7j8n8ebt/public_html/accuware/mautic/index.php(24): Stack\run(Object(Stack\StackedHttpKernel))
#12 {main}
[08-Sep-2020 21:22:09 UTC] Database connection error (code #0) - in file /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/AppKernel.php - at line 100
[24-Sep-2020 12:38:40 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:38:42 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:38:44 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:38:49 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:38:49 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:38:56 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:53:15 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 12:53:16 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 13:00:58 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 13:04:48 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 13:08:56 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 13:23:21 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[24-Sep-2020 13:37:31 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[28-Sep-2020 06:37:16 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 13:58:43 UTC] PHP Warning:  "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php on line 444
[29-Sep-2020 13:58:45 UTC] PHP Warning:  "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php on line 444
[29-Sep-2020 13:58:48 UTC] PHP Warning:  "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php on line 444
[29-Sep-2020 13:59:17 UTC] PHP Warning:  "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php on line 444
[29-Sep-2020 14:41:05 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:41:08 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:41:08 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:41:09 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:41:10 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:41:12 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:42:05 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:51:42 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 14:55:07 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 15:14:08 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[29-Sep-2020 15:40:56 UTC] PHP Notice:  Undefined index: ct in /home/wfuf7j8n8ebt/public_html/accuware/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 451
[02-Oct-2020 18:56:01 UTC] PHP Warning - require(/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php): failed to open stream: No such file or directory - in file /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php - at line 5824
[02-Oct-2020 18:56:01 UTC] PHP Warning:  require(/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php): failed to open stream: No such file or directory in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:56:01 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:56:01 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:56:01 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:59:15 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:59:23 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:59:26 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 18:59:57 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 19:00:11 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 19:00:15 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 19:00:51 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 19:08:41 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 19:09:46 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824
[02-Oct-2020 19:09:54 UTC] PHP Fatal error:  require(): Failed opening required '/home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/removed-ids.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/wfuf7j8n8ebt/public_html/accuware/mautic/var/cache/prod/ContainerVimqzsq/appProdProjectContainer.php on line 5824

**Comment by colourfulowl** [comment]
Hi @Dylan-86 You error returns the following "SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket". 

This is usually a simple connection failure error. Can you make sure your /app/config/local.php file has the correct SQL login details?

**Comment by Dylan-86** [comment]
Yes, I confirm it has the correct SQL login details indeed.

**Comment by RCheesley** [comment]
Hi there,

First thing: Please post support requests at https://forum.mautic.org/c/support rather than in Github. 

Second: Please follow the steps here: https://docs.mautic.org/en/troubleshooting/update-failed

If that does not resolve the issue, please raise a post on the forum and the community will be able to help troubleshoot further.

**Comment by trianity** [comment]
The undefined index: ct issue is described here:
https://github.com/mautic/mautic/issues/7841
