### ISSUE TITLE
Mautic 4: Unable to create social media (Twitter) mention

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9830]
## Bug Description
⚠️ This relates to Mautic 4.0-alpha1

| Q   | A
| --- | ---
| Mautic version | 4.0-alpha1
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Create a social media mention monitor
2. Save - see the error below
3. Try to edit or delete - same error
 
### Log errors
```
[2021-03-25 17:40:03] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.core.model.auditLog is not a registered container key." at /var/www/html/app/bundles/CoreBundle/Factory/ModelFactory.php line 53 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.core.model.auditLog is not a registered container key. at /var/www/html/app/bundles/CoreBundle/Factory/ModelFactory.php:53)
[stacktrace]
#0 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(152): Mautic\\CoreBundle\\Factory\\ModelFactory->getModel('core.auditLog')
#1 /var/www/html/plugins/MauticSocialBundle/Controller/MonitoringController.php(666): Mautic\\CoreBundle\\Controller\\CommonController->getModel('core.auditLog')
#2 /var/www/html/plugins/MauticSocialBundle/Controller/MonitoringController.php(163): MauticPlugin\\MauticSocialBundle\\Controller\\MonitoringController->updateAuditLog(Object(MauticPlugin\\MauticSocialBundle\\Entity\\Monitoring), 'create')
#3 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): MauticPlugin\\MauticSocialBundle\\Controller\\MonitoringController->newAction(0, '')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#15 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#16 {main}
"} 
```

**Comment by RCheesley** [comment]
Same issue for creating a hashtag monitor!
