### ISSUE TITLE
Automatic MaxMind GeoLite 2 City: corrupted tar file

### ISSUE THREAD

**Issue by rvalle** [mautic/mautic#9881]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | latest/docker
| PHP version | latest/docker
| Browser | firefox

### Steps to reproduce
1. Open System Settings/Lookup IP Service
2. Setup Key as authentication
3. Click on Fetch IP lookup data store
4. Alternatively, use the console to CLI to download
 
### Log errors
```
root@1c58272cc4f0:/var/www/html/app# php console mautic:iplookup:download
UnexpectedValueException: phar error: "/var/www/html/app/cache/prod/unpack/temp.tar.gz" is a corrupted tar file (checksum mismatch of file "HTTP/2 200 
date: Tue, 06 Apr 2021 08:41:02 GMT
content-type: application/gzip
content-length: 30") in /var/www/html/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php:110
Stack trace:
#0 /var/www/html/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php(110): PharData->__construct('/var/www/html/a...')
#1 /var/www/html/app/bundles/CoreBundle/Command/UpdateIpDataStoreCommand.php(50): Mautic\CoreBundle\IpLookup\AbstractLocalDataLookup->downloadRemoteDataStore()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(242): Mautic\CoreBundle\Command\UpdateIpDataStoreCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/console/Application.php(861): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CoreBundle\Command\UpdateIpDataStoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(84): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/app/console(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}
Automatically fetching the IP lookup data failed. Download https://download.maxmind.com/app/geoip_download?license_key=XXXXXXXXXX&edition_id=GeoLite2-City&suffix=tar.gz, extract if necessary, and upload to /var/www/html/app/cache/prod/../ip_data/GeoLite2-City.mmdb.
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by rvalle** [comment]
I have been reading the threads about the recent addition of KEY to download the MaxMind location store.

Still I don't see any specific issue related to this tar file corruption.

When inspecting the offending tar file, I noticed the following:

```
more cache/prod/unpack/temp.tar.gz 
HTTP/2 200 
date: Tue, 06 Apr 2021 08:41:02 GMT
content-type: application/gzip
content-length: 30086650
set-cookie: __cfduid=d589c4f5e157e62facbcf3143cb3499341617698461; expires=Thu, 06-May-21 08:41:01 GMT; path=/; domain=.maxmind.com; HttpOnly
; SameSite=Lax
cf-ray: 63b9b6fa3f399736-FRA
accept-ranges: bytes
cache-control: private, max-age=0
content-disposition: attachment; filename=GeoLite2-City_20210406.tar.gz
etag: "7cc7e68e1f41e023ef417771f565548e"
expires: Tue, 06 Apr 2021 08:41:02 GMT
last-modified: Mon, 05 Apr 2021 19:31:14 GMT
cf-cache-status: DYNAMIC
cf-request-id: 0947f0b06200009736a53aa000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-maxmind-worker: enabled
server: cloudflare

<<binnary data follows>>
```

Which looks like some HTTP headers got into the stream meant to hold the body only. then I run the following test:

```
cat cache/prod/unpack/temp.tar.gz | tail -n +19 | tar tvzf -
drwxrwxr-x 0/0               0 2021-04-05 19:31 GeoLite2-City_20210406/
-rw-r--r-- 0/0             116 2021-04-05 19:31 GeoLite2-City_20210406/README.txt
-rw-r--r-- 0/0              55 2021-04-05 19:31 GeoLite2-City_20210406/COPYRIGHT.txt
-rw-r--r-- 0/0        61806619 2021-04-05 19:31 GeoLite2-City_20210406/GeoLite2-City.mmdb
-rw-r--r-- 0/0             398 2021-04-05 19:31 GeoLite2-City_20210406/LICENSE.txt
```

Which seems like the Body is within the temporal file, and it is intact.

I have no clue why this is happening. 

I have an outgoing HTTP_PROXY setup in my docker image, and I have confirmed that the request was correctly forwarded to the proxy. perhaps this could be related?
